const packageDir = new URL('../', import.meta.url)
const sourceUrl = new URL(
  'node_modules/csstype-extra/src/index.d.ts',
  packageDir,
)
const outputUrl = new URL(
  'src/types/props/generated-css-properties.ts',
  packageDir,
)

const source = await Bun.file(sourceUrl).text()
const propertiesEnd = source.indexOf('export type AtRules')
if (propertiesEnd === -1) {
  throw new Error('Unable to find the end of csstype-extra properties')
}

const declarations = new Map<string, string>()
for (const match of source
  .slice(0, propertiesEnd)
  .matchAll(
    /^ {2}([A-Za-z][A-Za-z0-9]*)\?: (Property\.[A-Za-z0-9]+ \| undefined)$/gm,
  )) {
  const [, name, value] = match
  const previous = declarations.get(name)
  if (previous && previous !== value) {
    throw new Error(`Conflicting declarations for ${name}`)
  }
  declarations.set(name, value)
}

if (declarations.size < 600) {
  throw new Error(
    `Expected at least 600 CSS properties, found ${declarations.size}`,
  )
}

const lines = [
  '// Generated by scripts/generate-css-properties.ts. Do not edit directly.',
  "import type { Property } from 'csstype-extra'",
  '',
  "import type { ResponsiveValue } from '../responsive-value'",
  '',
  'export interface DevupCssProperties {',
  ...[...declarations].map(([name, value]) => {
    const declaration = `  ${name}?: ResponsiveValue<${value}>`
    return declaration.length > 80
      ? `  ${name}?: ResponsiveValue<\n    ${value}\n  >`
      : declaration
  }),
  '}',
  '',
]

const output = lines.join('\n')
if (Bun.argv.includes('--check')) {
  const current = await Bun.file(outputUrl).text()
  if (current !== output) {
    throw new Error(
      'Generated CSS properties are stale. Run bun run generate:css-types.',
    )
  }
} else {
  await Bun.write(outputUrl, output)
}
