// Generated by scripts/generate-css-properties.ts. Do not edit directly.
import type { Property } from 'csstype-extra'

import type { ResponsiveValue } from '../responsive-value'

export interface DevupCssProperties {
  accentColor?: ResponsiveValue<Property.AccentColor | undefined>
  alignContent?: ResponsiveValue<Property.AlignContent | undefined>
  alignItems?: ResponsiveValue<Property.AlignItems | undefined>
  alignSelf?: ResponsiveValue<Property.AlignSelf | undefined>
  alignTracks?: ResponsiveValue<Property.AlignTracks | undefined>
  alignmentBaseline?: ResponsiveValue<Property.AlignmentBaseline | undefined>
  all?: ResponsiveValue<Property.All | undefined>
  anchorName?: ResponsiveValue<Property.AnchorName | undefined>
  anchorScope?: ResponsiveValue<Property.AnchorScope | undefined>
  animationComposition?: ResponsiveValue<
    Property.AnimationComposition | undefined
  >
  animationDelay?: ResponsiveValue<Property.AnimationDelay | undefined>
  animationDirection?: ResponsiveValue<Property.AnimationDirection | undefined>
  animationDuration?: ResponsiveValue<Property.AnimationDuration | undefined>
  animationFillMode?: ResponsiveValue<Property.AnimationFillMode | undefined>
  animationIterationCount?: ResponsiveValue<
    Property.AnimationIterationCount | undefined
  >
  animationName?: ResponsiveValue<Property.AnimationName | undefined>
  animationPlayState?: ResponsiveValue<Property.AnimationPlayState | undefined>
  animationRangeEnd?: ResponsiveValue<Property.AnimationRangeEnd | undefined>
  animationRangeStart?: ResponsiveValue<
    Property.AnimationRangeStart | undefined
  >
  animationTimeline?: ResponsiveValue<Property.AnimationTimeline | undefined>
  animationTimingFunction?: ResponsiveValue<
    Property.AnimationTimingFunction | undefined
  >
  animationTrigger?: ResponsiveValue<Property.AnimationTrigger | undefined>
  appearance?: ResponsiveValue<Property.Appearance | undefined>
  aspectRatio?: ResponsiveValue<Property.AspectRatio | undefined>
  backdropFilter?: ResponsiveValue<Property.BackdropFilter | undefined>
  backfaceVisibility?: ResponsiveValue<Property.BackfaceVisibility | undefined>
  backgroundAttachment?: ResponsiveValue<
    Property.BackgroundAttachment | undefined
  >
  backgroundBlendMode?: ResponsiveValue<
    Property.BackgroundBlendMode | undefined
  >
  backgroundClip?: ResponsiveValue<Property.BackgroundClip | undefined>
  backgroundColor?: ResponsiveValue<Property.BackgroundColor | undefined>
  backgroundImage?: ResponsiveValue<Property.BackgroundImage | undefined>
  backgroundOrigin?: ResponsiveValue<Property.BackgroundOrigin | undefined>
  backgroundPositionX?: ResponsiveValue<
    Property.BackgroundPositionX | undefined
  >
  backgroundPositionY?: ResponsiveValue<
    Property.BackgroundPositionY | undefined
  >
  backgroundRepeat?: ResponsiveValue<Property.BackgroundRepeat | undefined>
  backgroundSize?: ResponsiveValue<Property.BackgroundSize | undefined>
  baselineShift?: ResponsiveValue<Property.BaselineShift | undefined>
  baselineSource?: ResponsiveValue<Property.BaselineSource | undefined>
  blockSize?: ResponsiveValue<Property.BlockSize | undefined>
  borderBlockEndColor?: ResponsiveValue<
    Property.BorderBlockEndColor | undefined
  >
  borderBlockEndStyle?: ResponsiveValue<
    Property.BorderBlockEndStyle | undefined
  >
  borderBlockEndWidth?: ResponsiveValue<
    Property.BorderBlockEndWidth | undefined
  >
  borderBlockStartColor?: ResponsiveValue<
    Property.BorderBlockStartColor | undefined
  >
  borderBlockStartStyle?: ResponsiveValue<
    Property.BorderBlockStartStyle | undefined
  >
  borderBlockStartWidth?: ResponsiveValue<
    Property.BorderBlockStartWidth | undefined
  >
  borderBottomColor?: ResponsiveValue<Property.BorderBottomColor | undefined>
  borderBottomLeftRadius?: ResponsiveValue<
    Property.BorderBottomLeftRadius | undefined
  >
  borderBottomRightRadius?: ResponsiveValue<
    Property.BorderBottomRightRadius | undefined
  >
  borderBottomStyle?: ResponsiveValue<Property.BorderBottomStyle | undefined>
  borderBottomWidth?: ResponsiveValue<Property.BorderBottomWidth | undefined>
  borderCollapse?: ResponsiveValue<Property.BorderCollapse | undefined>
  borderEndEndRadius?: ResponsiveValue<Property.BorderEndEndRadius | undefined>
  borderEndStartRadius?: ResponsiveValue<
    Property.BorderEndStartRadius | undefined
  >
  borderImageOutset?: ResponsiveValue<Property.BorderImageOutset | undefined>
  borderImageRepeat?: ResponsiveValue<Property.BorderImageRepeat | undefined>
  borderImageSlice?: ResponsiveValue<Property.BorderImageSlice | undefined>
  borderImageSource?: ResponsiveValue<Property.BorderImageSource | undefined>
  borderImageWidth?: ResponsiveValue<Property.BorderImageWidth | undefined>
  borderInlineEndColor?: ResponsiveValue<
    Property.BorderInlineEndColor | undefined
  >
  borderInlineEndStyle?: ResponsiveValue<
    Property.BorderInlineEndStyle | undefined
  >
  borderInlineEndWidth?: ResponsiveValue<
    Property.BorderInlineEndWidth | undefined
  >
  borderInlineStartColor?: ResponsiveValue<
    Property.BorderInlineStartColor | undefined
  >
  borderInlineStartStyle?: ResponsiveValue<
    Property.BorderInlineStartStyle | undefined
  >
  borderInlineStartWidth?: ResponsiveValue<
    Property.BorderInlineStartWidth | undefined
  >
  borderLeftColor?: ResponsiveValue<Property.BorderLeftColor | undefined>
  borderLeftStyle?: ResponsiveValue<Property.BorderLeftStyle | undefined>
  borderLeftWidth?: ResponsiveValue<Property.BorderLeftWidth | undefined>
  borderRightColor?: ResponsiveValue<Property.BorderRightColor | undefined>
  borderRightStyle?: ResponsiveValue<Property.BorderRightStyle | undefined>
  borderRightWidth?: ResponsiveValue<Property.BorderRightWidth | undefined>
  borderShape?: ResponsiveValue<Property.BorderShape | undefined>
  borderSpacing?: ResponsiveValue<Property.BorderSpacing | undefined>
  borderStartEndRadius?: ResponsiveValue<
    Property.BorderStartEndRadius | undefined
  >
  borderStartStartRadius?: ResponsiveValue<
    Property.BorderStartStartRadius | undefined
  >
  borderTopColor?: ResponsiveValue<Property.BorderTopColor | undefined>
  borderTopLeftRadius?: ResponsiveValue<
    Property.BorderTopLeftRadius | undefined
  >
  borderTopRightRadius?: ResponsiveValue<
    Property.BorderTopRightRadius | undefined
  >
  borderTopStyle?: ResponsiveValue<Property.BorderTopStyle | undefined>
  borderTopWidth?: ResponsiveValue<Property.BorderTopWidth | undefined>
  bottom?: ResponsiveValue<Property.Bottom | undefined>
  WebkitBoxAlign?: ResponsiveValue<Property.WebkitBoxAlign | undefined>
  MozBoxAlign?: ResponsiveValue<Property.MozBoxAlign | undefined>
  boxAlign?: ResponsiveValue<Property.BoxAlign | undefined>
  boxDecorationBreak?: ResponsiveValue<Property.BoxDecorationBreak | undefined>
  WebkitBoxDirection?: ResponsiveValue<Property.WebkitBoxDirection | undefined>
  MozBoxDirection?: ResponsiveValue<Property.MozBoxDirection | undefined>
  boxDirection?: ResponsiveValue<Property.BoxDirection | undefined>
  WebkitBoxFlex?: ResponsiveValue<Property.WebkitBoxFlex | undefined>
  MozBoxFlex?: ResponsiveValue<Property.MozBoxFlex | undefined>
  boxFlex?: ResponsiveValue<Property.BoxFlex | undefined>
  WebkitBoxFlexGroup?: ResponsiveValue<Property.WebkitBoxFlexGroup | undefined>
  MozBoxFlexGroup?: ResponsiveValue<Property.MozBoxFlexGroup | undefined>
  boxFlexGroup?: ResponsiveValue<Property.BoxFlexGroup | undefined>
  WebkitBoxLines?: ResponsiveValue<Property.WebkitBoxLines | undefined>
  MozBoxLines?: ResponsiveValue<Property.MozBoxLines | undefined>
  boxLines?: ResponsiveValue<Property.BoxLines | undefined>
  WebkitBoxOrdinalGroup?: ResponsiveValue<
    Property.WebkitBoxOrdinalGroup | undefined
  >
  MozBoxOrdinalGroup?: ResponsiveValue<Property.MozBoxOrdinalGroup | undefined>
  boxOrdinalGroup?: ResponsiveValue<Property.BoxOrdinalGroup | undefined>
  WebkitBoxOrient?: ResponsiveValue<Property.WebkitBoxOrient | undefined>
  MozBoxOrient?: ResponsiveValue<Property.MozBoxOrient | undefined>
  boxOrient?: ResponsiveValue<Property.BoxOrient | undefined>
  WebkitBoxPack?: ResponsiveValue<Property.WebkitBoxPack | undefined>
  MozBoxPack?: ResponsiveValue<Property.MozBoxPack | undefined>
  boxPack?: ResponsiveValue<Property.BoxPack | undefined>
  boxShadow?: ResponsiveValue<Property.BoxShadow | undefined>
  boxSizing?: ResponsiveValue<Property.BoxSizing | undefined>
  breakAfter?: ResponsiveValue<Property.BreakAfter | undefined>
  breakBefore?: ResponsiveValue<Property.BreakBefore | undefined>
  breakInside?: ResponsiveValue<Property.BreakInside | undefined>
  captionSide?: ResponsiveValue<Property.CaptionSide | undefined>
  caretAnimation?: ResponsiveValue<Property.CaretAnimation | undefined>
  caretColor?: ResponsiveValue<Property.CaretColor | undefined>
  caretShape?: ResponsiveValue<Property.CaretShape | undefined>
  clear?: ResponsiveValue<Property.Clear | undefined>
  clip?: ResponsiveValue<Property.Clip | undefined>
  clipPath?: ResponsiveValue<Property.ClipPath | undefined>
  clipRule?: ResponsiveValue<Property.ClipRule | undefined>
  color?: ResponsiveValue<Property.Color | undefined>
  colorInterpolationFilters?: ResponsiveValue<
    Property.ColorInterpolationFilters | undefined
  >
  colorScheme?: ResponsiveValue<Property.ColorScheme | undefined>
  columnCount?: ResponsiveValue<Property.ColumnCount | undefined>
  columnFill?: ResponsiveValue<Property.ColumnFill | undefined>
  columnGap?: ResponsiveValue<Property.ColumnGap | undefined>
  columnHeight?: ResponsiveValue<Property.ColumnHeight | undefined>
  columnRuleColor?: ResponsiveValue<Property.ColumnRuleColor | undefined>
  columnRuleStyle?: ResponsiveValue<Property.ColumnRuleStyle | undefined>
  columnRuleWidth?: ResponsiveValue<Property.ColumnRuleWidth | undefined>
  columnSpan?: ResponsiveValue<Property.ColumnSpan | undefined>
  columnWidth?: ResponsiveValue<Property.ColumnWidth | undefined>
  columnWrap?: ResponsiveValue<Property.ColumnWrap | undefined>
  contain?: ResponsiveValue<Property.Contain | undefined>
  containIntrinsicBlockSize?: ResponsiveValue<
    Property.ContainIntrinsicBlockSize | undefined
  >
  containIntrinsicHeight?: ResponsiveValue<
    Property.ContainIntrinsicHeight | undefined
  >
  containIntrinsicInlineSize?: ResponsiveValue<
    Property.ContainIntrinsicInlineSize | undefined
  >
  containIntrinsicWidth?: ResponsiveValue<
    Property.ContainIntrinsicWidth | undefined
  >
  containerName?: ResponsiveValue<Property.ContainerName | undefined>
  containerType?: ResponsiveValue<Property.ContainerType | undefined>
  content?: ResponsiveValue<Property.Content | undefined>
  contentVisibility?: ResponsiveValue<Property.ContentVisibility | undefined>
  cornerBottomLeftShape?: ResponsiveValue<
    Property.CornerBottomLeftShape | undefined
  >
  cornerBottomRightShape?: ResponsiveValue<
    Property.CornerBottomRightShape | undefined
  >
  cornerEndEndShape?: ResponsiveValue<Property.CornerEndEndShape | undefined>
  cornerEndStartShape?: ResponsiveValue<
    Property.CornerEndStartShape | undefined
  >
  cornerStartStartShape?: ResponsiveValue<
    Property.CornerStartStartShape | undefined
  >
  cornerStartEndShape?: ResponsiveValue<
    Property.CornerStartEndShape | undefined
  >
  cornerTopLeftShape?: ResponsiveValue<Property.CornerTopLeftShape | undefined>
  cornerTopRightShape?: ResponsiveValue<
    Property.CornerTopRightShape | undefined
  >
  counterIncrement?: ResponsiveValue<Property.CounterIncrement | undefined>
  counterReset?: ResponsiveValue<Property.CounterReset | undefined>
  counterSet?: ResponsiveValue<Property.CounterSet | undefined>
  cursor?: ResponsiveValue<Property.Cursor | undefined>
  cx?: ResponsiveValue<Property.Cx | undefined>
  cy?: ResponsiveValue<Property.Cy | undefined>
  d?: ResponsiveValue<Property.D | undefined>
  direction?: ResponsiveValue<Property.Direction | undefined>
  display?: ResponsiveValue<Property.Display | undefined>
  dominantBaseline?: ResponsiveValue<Property.DominantBaseline | undefined>
  dynamicRangeLimit?: ResponsiveValue<Property.DynamicRangeLimit | undefined>
  emptyCells?: ResponsiveValue<Property.EmptyCells | undefined>
  fieldSizing?: ResponsiveValue<Property.FieldSizing | undefined>
  fill?: ResponsiveValue<Property.Fill | undefined>
  fillOpacity?: ResponsiveValue<Property.FillOpacity | undefined>
  fillRule?: ResponsiveValue<Property.FillRule | undefined>
  filter?: ResponsiveValue<Property.Filter | undefined>
  flexBasis?: ResponsiveValue<Property.FlexBasis | undefined>
  flexDirection?: ResponsiveValue<Property.FlexDirection | undefined>
  flexGrow?: ResponsiveValue<Property.FlexGrow | undefined>
  flexLineCount?: ResponsiveValue<Property.FlexLineCount | undefined>
  flexShrink?: ResponsiveValue<Property.FlexShrink | undefined>
  flexWrap?: ResponsiveValue<Property.FlexWrap | undefined>
  float?: ResponsiveValue<Property.Float | undefined>
  floodColor?: ResponsiveValue<Property.FloodColor | undefined>
  floodOpacity?: ResponsiveValue<Property.FloodOpacity | undefined>
  fontFamily?: ResponsiveValue<Property.FontFamily | undefined>
  fontFeatureSettings?: ResponsiveValue<
    Property.FontFeatureSettings | undefined
  >
  fontKerning?: ResponsiveValue<Property.FontKerning | undefined>
  fontLanguageOverride?: ResponsiveValue<
    Property.FontLanguageOverride | undefined
  >
  fontOpticalSizing?: ResponsiveValue<Property.FontOpticalSizing | undefined>
  fontPalette?: ResponsiveValue<Property.FontPalette | undefined>
  fontSize?: ResponsiveValue<Property.FontSize | undefined>
  fontSizeAdjust?: ResponsiveValue<Property.FontSizeAdjust | undefined>
  fontSmooth?: ResponsiveValue<Property.FontSmooth | undefined>
  fontStretch?: ResponsiveValue<Property.FontStretch | undefined>
  fontStyle?: ResponsiveValue<Property.FontStyle | undefined>
  fontSynthesis?: ResponsiveValue<Property.FontSynthesis | undefined>
  fontSynthesisPosition?: ResponsiveValue<
    Property.FontSynthesisPosition | undefined
  >
  fontSynthesisSmallCaps?: ResponsiveValue<
    Property.FontSynthesisSmallCaps | undefined
  >
  fontSynthesisStyle?: ResponsiveValue<Property.FontSynthesisStyle | undefined>
  fontSynthesisWeight?: ResponsiveValue<
    Property.FontSynthesisWeight | undefined
  >
  fontVariant?: ResponsiveValue<Property.FontVariant | undefined>
  fontVariantAlternates?: ResponsiveValue<
    Property.FontVariantAlternates | undefined
  >
  fontVariantCaps?: ResponsiveValue<Property.FontVariantCaps | undefined>
  fontVariantEastAsian?: ResponsiveValue<
    Property.FontVariantEastAsian | undefined
  >
  fontVariantEmoji?: ResponsiveValue<Property.FontVariantEmoji | undefined>
  fontVariantLigatures?: ResponsiveValue<
    Property.FontVariantLigatures | undefined
  >
  fontVariantNumeric?: ResponsiveValue<Property.FontVariantNumeric | undefined>
  fontVariantPosition?: ResponsiveValue<
    Property.FontVariantPosition | undefined
  >
  fontVariationSettings?: ResponsiveValue<
    Property.FontVariationSettings | undefined
  >
  fontWeight?: ResponsiveValue<Property.FontWeight | undefined>
  fontWidth?: ResponsiveValue<Property.FontWidth | undefined>
  forcedColorAdjust?: ResponsiveValue<Property.ForcedColorAdjust | undefined>
  frameSizing?: ResponsiveValue<Property.FrameSizing | undefined>
  gridAutoColumns?: ResponsiveValue<Property.GridAutoColumns | undefined>
  gridAutoFlow?: ResponsiveValue<Property.GridAutoFlow | undefined>
  gridAutoRows?: ResponsiveValue<Property.GridAutoRows | undefined>
  gridColumnEnd?: ResponsiveValue<Property.GridColumnEnd | undefined>
  gridColumnGap?: ResponsiveValue<Property.GridColumnGap | undefined>
  gridColumnStart?: ResponsiveValue<Property.GridColumnStart | undefined>
  gridRowEnd?: ResponsiveValue<Property.GridRowEnd | undefined>
  gridRowGap?: ResponsiveValue<Property.GridRowGap | undefined>
  gridRowStart?: ResponsiveValue<Property.GridRowStart | undefined>
  gridTemplateAreas?: ResponsiveValue<Property.GridTemplateAreas | undefined>
  gridTemplateColumns?: ResponsiveValue<
    Property.GridTemplateColumns | undefined
  >
  gridTemplateRows?: ResponsiveValue<Property.GridTemplateRows | undefined>
  hangingPunctuation?: ResponsiveValue<Property.HangingPunctuation | undefined>
  height?: ResponsiveValue<Property.Height | undefined>
  hyphenateCharacter?: ResponsiveValue<Property.HyphenateCharacter | undefined>
  hyphenateLimitChars?: ResponsiveValue<
    Property.HyphenateLimitChars | undefined
  >
  hyphens?: ResponsiveValue<Property.Hyphens | undefined>
  imageOrientation?: ResponsiveValue<Property.ImageOrientation | undefined>
  imageRendering?: ResponsiveValue<Property.ImageRendering | undefined>
  imageResolution?: ResponsiveValue<Property.ImageResolution | undefined>
  imeMode?: ResponsiveValue<Property.ImeMode | undefined>
  initialLetter?: ResponsiveValue<Property.InitialLetter | undefined>
  initialLetterAlign?: ResponsiveValue<Property.InitialLetterAlign | undefined>
  inlineSize?: ResponsiveValue<Property.InlineSize | undefined>
  insetBlockEnd?: ResponsiveValue<Property.InsetBlockEnd | undefined>
  insetBlockStart?: ResponsiveValue<Property.InsetBlockStart | undefined>
  insetInlineEnd?: ResponsiveValue<Property.InsetInlineEnd | undefined>
  insetInlineStart?: ResponsiveValue<Property.InsetInlineStart | undefined>
  interpolateSize?: ResponsiveValue<Property.InterpolateSize | undefined>
  isolation?: ResponsiveValue<Property.Isolation | undefined>
  interactivity?: ResponsiveValue<Property.Interactivity | undefined>
  interestDelayEnd?: ResponsiveValue<Property.InterestDelayEnd | undefined>
  interestDelayStart?: ResponsiveValue<Property.InterestDelayStart | undefined>
  justifyContent?: ResponsiveValue<Property.JustifyContent | undefined>
  justifyItems?: ResponsiveValue<Property.JustifyItems | undefined>
  justifySelf?: ResponsiveValue<Property.JustifySelf | undefined>
  justifyTracks?: ResponsiveValue<Property.JustifyTracks | undefined>
  left?: ResponsiveValue<Property.Left | undefined>
  letterSpacing?: ResponsiveValue<Property.LetterSpacing | undefined>
  lightingColor?: ResponsiveValue<Property.LightingColor | undefined>
  lineBreak?: ResponsiveValue<Property.LineBreak | undefined>
  lineClamp?: ResponsiveValue<Property.LineClamp | undefined>
  lineHeight?: ResponsiveValue<Property.LineHeight | undefined>
  lineHeightStep?: ResponsiveValue<Property.LineHeightStep | undefined>
  linkParameters?: ResponsiveValue<Property.LinkParameters | undefined>
  listStyleImage?: ResponsiveValue<Property.ListStyleImage | undefined>
  listStylePosition?: ResponsiveValue<Property.ListStylePosition | undefined>
  listStyleType?: ResponsiveValue<Property.ListStyleType | undefined>
  marginBlockEnd?: ResponsiveValue<Property.MarginBlockEnd | undefined>
  marginBlockStart?: ResponsiveValue<Property.MarginBlockStart | undefined>
  marginBottom?: ResponsiveValue<Property.MarginBottom | undefined>
  marginInlineEnd?: ResponsiveValue<Property.MarginInlineEnd | undefined>
  marginInlineStart?: ResponsiveValue<Property.MarginInlineStart | undefined>
  marginLeft?: ResponsiveValue<Property.MarginLeft | undefined>
  marginRight?: ResponsiveValue<Property.MarginRight | undefined>
  marginTop?: ResponsiveValue<Property.MarginTop | undefined>
  marginTrim?: ResponsiveValue<Property.MarginTrim | undefined>
  marker?: ResponsiveValue<Property.Marker | undefined>
  markerEnd?: ResponsiveValue<Property.MarkerEnd | undefined>
  markerMid?: ResponsiveValue<Property.MarkerMid | undefined>
  markerStart?: ResponsiveValue<Property.MarkerStart | undefined>
  maskBorderMode?: ResponsiveValue<Property.MaskBorderMode | undefined>
  maskBorderOutset?: ResponsiveValue<Property.MaskBorderOutset | undefined>
  maskBorderRepeat?: ResponsiveValue<Property.MaskBorderRepeat | undefined>
  maskBorderSlice?: ResponsiveValue<Property.MaskBorderSlice | undefined>
  maskBorderSource?: ResponsiveValue<Property.MaskBorderSource | undefined>
  maskBorderWidth?: ResponsiveValue<Property.MaskBorderWidth | undefined>
  maskClip?: ResponsiveValue<Property.MaskClip | undefined>
  maskComposite?: ResponsiveValue<Property.MaskComposite | undefined>
  maskImage?: ResponsiveValue<Property.MaskImage | undefined>
  maskMode?: ResponsiveValue<Property.MaskMode | undefined>
  maskOrigin?: ResponsiveValue<Property.MaskOrigin | undefined>
  maskPosition?: ResponsiveValue<Property.MaskPosition | undefined>
  maskRepeat?: ResponsiveValue<Property.MaskRepeat | undefined>
  maskSize?: ResponsiveValue<Property.MaskSize | undefined>
  maskType?: ResponsiveValue<Property.MaskType | undefined>
  masonryAutoFlow?: ResponsiveValue<Property.MasonryAutoFlow | undefined>
  mathDepth?: ResponsiveValue<Property.MathDepth | undefined>
  mathShift?: ResponsiveValue<Property.MathShift | undefined>
  mathStyle?: ResponsiveValue<Property.MathStyle | undefined>
  maxBlockSize?: ResponsiveValue<Property.MaxBlockSize | undefined>
  maxHeight?: ResponsiveValue<Property.MaxHeight | undefined>
  maxInlineSize?: ResponsiveValue<Property.MaxInlineSize | undefined>
  maxLines?: ResponsiveValue<Property.MaxLines | undefined>
  maxWidth?: ResponsiveValue<Property.MaxWidth | undefined>
  minBlockSize?: ResponsiveValue<Property.MinBlockSize | undefined>
  minHeight?: ResponsiveValue<Property.MinHeight | undefined>
  minInlineSize?: ResponsiveValue<Property.MinInlineSize | undefined>
  minWidth?: ResponsiveValue<Property.MinWidth | undefined>
  mixBlendMode?: ResponsiveValue<Property.MixBlendMode | undefined>
  objectFit?: ResponsiveValue<Property.ObjectFit | undefined>
  objectPosition?: ResponsiveValue<Property.ObjectPosition | undefined>
  objectViewBox?: ResponsiveValue<Property.ObjectViewBox | undefined>
  offsetAnchor?: ResponsiveValue<Property.OffsetAnchor | undefined>
  offsetDistance?: ResponsiveValue<Property.OffsetDistance | undefined>
  offsetPath?: ResponsiveValue<Property.OffsetPath | undefined>
  offsetPosition?: ResponsiveValue<Property.OffsetPosition | undefined>
  offsetRotate?: ResponsiveValue<Property.OffsetRotate | undefined>
  opacity?: ResponsiveValue<Property.Opacity | undefined>
  order?: ResponsiveValue<Property.Order | undefined>
  orphans?: ResponsiveValue<Property.Orphans | undefined>
  outlineColor?: ResponsiveValue<Property.OutlineColor | undefined>
  outlineOffset?: ResponsiveValue<Property.OutlineOffset | undefined>
  outlineStyle?: ResponsiveValue<Property.OutlineStyle | undefined>
  outlineWidth?: ResponsiveValue<Property.OutlineWidth | undefined>
  overflowAnchor?: ResponsiveValue<Property.OverflowAnchor | undefined>
  overflowBlock?: ResponsiveValue<Property.OverflowBlock | undefined>
  MozOverflowClipBox?: ResponsiveValue<Property.MozOverflowClipBox | undefined>
  overflowClipBox?: ResponsiveValue<Property.OverflowClipBox | undefined>
  overflowClipMargin?: ResponsiveValue<Property.OverflowClipMargin | undefined>
  overflowInline?: ResponsiveValue<Property.OverflowInline | undefined>
  overflowWrap?: ResponsiveValue<Property.OverflowWrap | undefined>
  overflowX?: ResponsiveValue<Property.OverflowX | undefined>
  overflowY?: ResponsiveValue<Property.OverflowY | undefined>
  overlay?: ResponsiveValue<Property.Overlay | undefined>
  overscrollBehaviorBlock?: ResponsiveValue<
    Property.OverscrollBehaviorBlock | undefined
  >
  overscrollBehaviorInline?: ResponsiveValue<
    Property.OverscrollBehaviorInline | undefined
  >
  overscrollBehaviorX?: ResponsiveValue<
    Property.OverscrollBehaviorX | undefined
  >
  overscrollBehaviorY?: ResponsiveValue<
    Property.OverscrollBehaviorY | undefined
  >
  paddingBlockEnd?: ResponsiveValue<Property.PaddingBlockEnd | undefined>
  paddingBlockStart?: ResponsiveValue<Property.PaddingBlockStart | undefined>
  paddingBottom?: ResponsiveValue<Property.PaddingBottom | undefined>
  paddingInlineEnd?: ResponsiveValue<Property.PaddingInlineEnd | undefined>
  paddingInlineStart?: ResponsiveValue<Property.PaddingInlineStart | undefined>
  paddingLeft?: ResponsiveValue<Property.PaddingLeft | undefined>
  paddingRight?: ResponsiveValue<Property.PaddingRight | undefined>
  paddingTop?: ResponsiveValue<Property.PaddingTop | undefined>
  page?: ResponsiveValue<Property.Page | undefined>
  pageBreakAfter?: ResponsiveValue<Property.PageBreakAfter | undefined>
  pageBreakBefore?: ResponsiveValue<Property.PageBreakBefore | undefined>
  pageBreakInside?: ResponsiveValue<Property.PageBreakInside | undefined>
  paintOrder?: ResponsiveValue<Property.PaintOrder | undefined>
  pathLength?: ResponsiveValue<Property.PathLength | undefined>
  perspective?: ResponsiveValue<Property.Perspective | undefined>
  perspectiveOrigin?: ResponsiveValue<Property.PerspectiveOrigin | undefined>
  pointerEvents?: ResponsiveValue<Property.PointerEvents | undefined>
  position?: ResponsiveValue<Property.Position | undefined>
  positionAnchor?: ResponsiveValue<Property.PositionAnchor | undefined>
  positionArea?: ResponsiveValue<Property.PositionArea | undefined>
  positionTryFallbacks?: ResponsiveValue<
    Property.PositionTryFallbacks | undefined
  >
  positionTryOrder?: ResponsiveValue<Property.PositionTryOrder | undefined>
  positionVisibility?: ResponsiveValue<Property.PositionVisibility | undefined>
  printColorAdjust?: ResponsiveValue<Property.PrintColorAdjust | undefined>
  quotes?: ResponsiveValue<Property.Quotes | undefined>
  r?: ResponsiveValue<Property.R | undefined>
  readingFlow?: ResponsiveValue<Property.ReadingFlow | undefined>
  readingOrder?: ResponsiveValue<Property.ReadingOrder | undefined>
  resize?: ResponsiveValue<Property.Resize | undefined>
  right?: ResponsiveValue<Property.Right | undefined>
  rotate?: ResponsiveValue<Property.Rotate | undefined>
  rowGap?: ResponsiveValue<Property.RowGap | undefined>
  rubyAlign?: ResponsiveValue<Property.RubyAlign | undefined>
  rubyMerge?: ResponsiveValue<Property.RubyMerge | undefined>
  rubyOverhang?: ResponsiveValue<Property.RubyOverhang | undefined>
  rubyPosition?: ResponsiveValue<Property.RubyPosition | undefined>
  rx?: ResponsiveValue<Property.Rx | undefined>
  ry?: ResponsiveValue<Property.Ry | undefined>
  scale?: ResponsiveValue<Property.Scale | undefined>
  scrollBehavior?: ResponsiveValue<Property.ScrollBehavior | undefined>
  scrollInitialTarget?: ResponsiveValue<
    Property.ScrollInitialTarget | undefined
  >
  scrollMarginBlockEnd?: ResponsiveValue<
    Property.ScrollMarginBlockEnd | undefined
  >
  scrollMarginBlockStart?: ResponsiveValue<
    Property.ScrollMarginBlockStart | undefined
  >
  scrollMarginBottom?: ResponsiveValue<Property.ScrollMarginBottom | undefined>
  scrollMarginInlineEnd?: ResponsiveValue<
    Property.ScrollMarginInlineEnd | undefined
  >
  scrollMarginInlineStart?: ResponsiveValue<
    Property.ScrollMarginInlineStart | undefined
  >
  scrollMarginLeft?: ResponsiveValue<Property.ScrollMarginLeft | undefined>
  scrollMarginRight?: ResponsiveValue<Property.ScrollMarginRight | undefined>
  scrollMarginTop?: ResponsiveValue<Property.ScrollMarginTop | undefined>
  scrollMarkerGroup?: ResponsiveValue<Property.ScrollMarkerGroup | undefined>
  scrollPaddingBlockEnd?: ResponsiveValue<
    Property.ScrollPaddingBlockEnd | undefined
  >
  scrollPaddingBlockStart?: ResponsiveValue<
    Property.ScrollPaddingBlockStart | undefined
  >
  scrollPaddingBottom?: ResponsiveValue<
    Property.ScrollPaddingBottom | undefined
  >
  scrollPaddingInlineEnd?: ResponsiveValue<
    Property.ScrollPaddingInlineEnd | undefined
  >
  scrollPaddingInlineStart?: ResponsiveValue<
    Property.ScrollPaddingInlineStart | undefined
  >
  scrollPaddingLeft?: ResponsiveValue<Property.ScrollPaddingLeft | undefined>
  scrollPaddingRight?: ResponsiveValue<Property.ScrollPaddingRight | undefined>
  scrollPaddingTop?: ResponsiveValue<Property.ScrollPaddingTop | undefined>
  scrollSnapAlign?: ResponsiveValue<Property.ScrollSnapAlign | undefined>
  scrollSnapCoordinate?: ResponsiveValue<
    Property.ScrollSnapCoordinate | undefined
  >
  scrollSnapDestination?: ResponsiveValue<
    Property.ScrollSnapDestination | undefined
  >
  scrollSnapPointsX?: ResponsiveValue<Property.ScrollSnapPointsX | undefined>
  scrollSnapPointsY?: ResponsiveValue<Property.ScrollSnapPointsY | undefined>
  scrollSnapStop?: ResponsiveValue<Property.ScrollSnapStop | undefined>
  scrollSnapType?: ResponsiveValue<Property.ScrollSnapType | undefined>
  scrollSnapTypeX?: ResponsiveValue<Property.ScrollSnapTypeX | undefined>
  scrollSnapTypeY?: ResponsiveValue<Property.ScrollSnapTypeY | undefined>
  scrollTargetGroup?: ResponsiveValue<Property.ScrollTargetGroup | undefined>
  scrollTimelineAxis?: ResponsiveValue<Property.ScrollTimelineAxis | undefined>
  scrollTimelineName?: ResponsiveValue<Property.ScrollTimelineName | undefined>
  scrollbarColor?: ResponsiveValue<Property.ScrollbarColor | undefined>
  scrollbarGutter?: ResponsiveValue<Property.ScrollbarGutter | undefined>
  scrollbarWidth?: ResponsiveValue<Property.ScrollbarWidth | undefined>
  shapeImageThreshold?: ResponsiveValue<
    Property.ShapeImageThreshold | undefined
  >
  shapeMargin?: ResponsiveValue<Property.ShapeMargin | undefined>
  shapeOutside?: ResponsiveValue<Property.ShapeOutside | undefined>
  shapeRendering?: ResponsiveValue<Property.ShapeRendering | undefined>
  speakAs?: ResponsiveValue<Property.SpeakAs | undefined>
  stopColor?: ResponsiveValue<Property.StopColor | undefined>
  stopOpacity?: ResponsiveValue<Property.StopOpacity | undefined>
  stroke?: ResponsiveValue<Property.Stroke | undefined>
  strokeColor?: ResponsiveValue<Property.StrokeColor | undefined>
  strokeDasharray?: ResponsiveValue<Property.StrokeDasharray | undefined>
  strokeDashoffset?: ResponsiveValue<Property.StrokeDashoffset | undefined>
  strokeLinecap?: ResponsiveValue<Property.StrokeLinecap | undefined>
  strokeLinejoin?: ResponsiveValue<Property.StrokeLinejoin | undefined>
  strokeMiterlimit?: ResponsiveValue<Property.StrokeMiterlimit | undefined>
  strokeOpacity?: ResponsiveValue<Property.StrokeOpacity | undefined>
  strokeWidth?: ResponsiveValue<Property.StrokeWidth | undefined>
  tabSize?: ResponsiveValue<Property.TabSize | undefined>
  tableLayout?: ResponsiveValue<Property.TableLayout | undefined>
  textAlign?: ResponsiveValue<Property.TextAlign | undefined>
  textAlignLast?: ResponsiveValue<Property.TextAlignLast | undefined>
  textAnchor?: ResponsiveValue<Property.TextAnchor | undefined>
  textAutospace?: ResponsiveValue<Property.TextAutospace | undefined>
  textBox?: ResponsiveValue<Property.TextBox | undefined>
  textBoxEdge?: ResponsiveValue<Property.TextBoxEdge | undefined>
  textBoxTrim?: ResponsiveValue<Property.TextBoxTrim | undefined>
  textCombineUpright?: ResponsiveValue<Property.TextCombineUpright | undefined>
  textDecorationColor?: ResponsiveValue<
    Property.TextDecorationColor | undefined
  >
  textDecorationInset?: ResponsiveValue<
    Property.TextDecorationInset | undefined
  >
  textDecorationLine?: ResponsiveValue<Property.TextDecorationLine | undefined>
  textDecorationSkip?: ResponsiveValue<Property.TextDecorationSkip | undefined>
  textDecorationSkipInk?: ResponsiveValue<
    Property.TextDecorationSkipInk | undefined
  >
  textDecorationStyle?: ResponsiveValue<
    Property.TextDecorationStyle | undefined
  >
  textDecorationThickness?: ResponsiveValue<
    Property.TextDecorationThickness | undefined
  >
  textEmphasisColor?: ResponsiveValue<Property.TextEmphasisColor | undefined>
  textEmphasisPosition?: ResponsiveValue<
    Property.TextEmphasisPosition | undefined
  >
  textEmphasisStyle?: ResponsiveValue<Property.TextEmphasisStyle | undefined>
  textFit?: ResponsiveValue<Property.TextFit | undefined>
  textIndent?: ResponsiveValue<Property.TextIndent | undefined>
  textJustify?: ResponsiveValue<Property.TextJustify | undefined>
  textOrientation?: ResponsiveValue<Property.TextOrientation | undefined>
  textOverflow?: ResponsiveValue<Property.TextOverflow | undefined>
  textRendering?: ResponsiveValue<Property.TextRendering | undefined>
  textShadow?: ResponsiveValue<Property.TextShadow | undefined>
  textSizeAdjust?: ResponsiveValue<Property.TextSizeAdjust | undefined>
  textSpacingTrim?: ResponsiveValue<Property.TextSpacingTrim | undefined>
  textTransform?: ResponsiveValue<Property.TextTransform | undefined>
  textUnderlineOffset?: ResponsiveValue<
    Property.TextUnderlineOffset | undefined
  >
  textUnderlinePosition?: ResponsiveValue<
    Property.TextUnderlinePosition | undefined
  >
  textWrapMode?: ResponsiveValue<Property.TextWrapMode | undefined>
  textWrapStyle?: ResponsiveValue<Property.TextWrapStyle | undefined>
  timelineScope?: ResponsiveValue<Property.TimelineScope | undefined>
  timelineTriggerName?: ResponsiveValue<
    Property.TimelineTriggerName | undefined
  >
  timelineTriggerSource?: ResponsiveValue<
    Property.TimelineTriggerSource | undefined
  >
  top?: ResponsiveValue<Property.Top | undefined>
  touchAction?: ResponsiveValue<Property.TouchAction | undefined>
  transform?: ResponsiveValue<Property.Transform | undefined>
  transformBox?: ResponsiveValue<Property.TransformBox | undefined>
  transformOrigin?: ResponsiveValue<Property.TransformOrigin | undefined>
  transformStyle?: ResponsiveValue<Property.TransformStyle | undefined>
  transitionBehavior?: ResponsiveValue<Property.TransitionBehavior | undefined>
  transitionDelay?: ResponsiveValue<Property.TransitionDelay | undefined>
  transitionDuration?: ResponsiveValue<Property.TransitionDuration | undefined>
  transitionProperty?: ResponsiveValue<Property.TransitionProperty | undefined>
  transitionTimingFunction?: ResponsiveValue<
    Property.TransitionTimingFunction | undefined
  >
  translate?: ResponsiveValue<Property.Translate | undefined>
  triggerScope?: ResponsiveValue<Property.TriggerScope | undefined>
  unicodeBidi?: ResponsiveValue<Property.UnicodeBidi | undefined>
  userSelect?: ResponsiveValue<Property.UserSelect | undefined>
  vectorEffect?: ResponsiveValue<Property.VectorEffect | undefined>
  verticalAlign?: ResponsiveValue<Property.VerticalAlign | undefined>
  viewTimelineAxis?: ResponsiveValue<Property.ViewTimelineAxis | undefined>
  viewTimelineInset?: ResponsiveValue<Property.ViewTimelineInset | undefined>
  viewTimelineName?: ResponsiveValue<Property.ViewTimelineName | undefined>
  viewTransitionClass?: ResponsiveValue<
    Property.ViewTransitionClass | undefined
  >
  viewTransitionName?: ResponsiveValue<Property.ViewTransitionName | undefined>
  viewTransitionScope?: ResponsiveValue<
    Property.ViewTransitionScope | undefined
  >
  visibility?: ResponsiveValue<Property.Visibility | undefined>
  whiteSpace?: ResponsiveValue<Property.WhiteSpace | undefined>
  whiteSpaceCollapse?: ResponsiveValue<Property.WhiteSpaceCollapse | undefined>
  widows?: ResponsiveValue<Property.Widows | undefined>
  width?: ResponsiveValue<Property.Width | undefined>
  willChange?: ResponsiveValue<Property.WillChange | undefined>
  wordBreak?: ResponsiveValue<Property.WordBreak | undefined>
  wordSpacing?: ResponsiveValue<Property.WordSpacing | undefined>
  wordWrap?: ResponsiveValue<Property.WordWrap | undefined>
  writingMode?: ResponsiveValue<Property.WritingMode | undefined>
  x?: ResponsiveValue<Property.X | undefined>
  y?: ResponsiveValue<Property.Y | undefined>
  zIndex?: ResponsiveValue<Property.ZIndex | undefined>
  zoom?: ResponsiveValue<Property.Zoom | undefined>
  animation?: ResponsiveValue<Property.Animation | undefined>
  animationRange?: ResponsiveValue<Property.AnimationRange | undefined>
  background?: ResponsiveValue<Property.Background | undefined>
  backgroundPosition?: ResponsiveValue<Property.BackgroundPosition | undefined>
  border?: ResponsiveValue<Property.Border | undefined>
  borderBlock?: ResponsiveValue<Property.BorderBlock | undefined>
  borderBlockColor?: ResponsiveValue<Property.BorderBlockColor | undefined>
  borderBlockEnd?: ResponsiveValue<Property.BorderBlockEnd | undefined>
  borderBlockStart?: ResponsiveValue<Property.BorderBlockStart | undefined>
  borderBlockStyle?: ResponsiveValue<Property.BorderBlockStyle | undefined>
  borderBlockWidth?: ResponsiveValue<Property.BorderBlockWidth | undefined>
  borderBottom?: ResponsiveValue<Property.BorderBottom | undefined>
  borderColor?: ResponsiveValue<Property.BorderColor | undefined>
  borderImage?: ResponsiveValue<Property.BorderImage | undefined>
  borderInline?: ResponsiveValue<Property.BorderInline | undefined>
  borderInlineColor?: ResponsiveValue<Property.BorderInlineColor | undefined>
  borderInlineEnd?: ResponsiveValue<Property.BorderInlineEnd | undefined>
  borderInlineStart?: ResponsiveValue<Property.BorderInlineStart | undefined>
  borderInlineStyle?: ResponsiveValue<Property.BorderInlineStyle | undefined>
  borderInlineWidth?: ResponsiveValue<Property.BorderInlineWidth | undefined>
  borderLeft?: ResponsiveValue<Property.BorderLeft | undefined>
  borderRadius?: ResponsiveValue<Property.BorderRadius | undefined>
  borderRight?: ResponsiveValue<Property.BorderRight | undefined>
  borderStyle?: ResponsiveValue<Property.BorderStyle | undefined>
  borderTop?: ResponsiveValue<Property.BorderTop | undefined>
  borderWidth?: ResponsiveValue<Property.BorderWidth | undefined>
  caret?: ResponsiveValue<Property.Caret | undefined>
  columnRule?: ResponsiveValue<Property.ColumnRule | undefined>
  columns?: ResponsiveValue<Property.Columns | undefined>
  containIntrinsicSize?: ResponsiveValue<
    Property.ContainIntrinsicSize | undefined
  >
  container?: ResponsiveValue<Property.Container | undefined>
  cornerBlockEndShape?: ResponsiveValue<
    Property.CornerBlockEndShape | undefined
  >
  cornerBlockStartShape?: ResponsiveValue<
    Property.CornerBlockStartShape | undefined
  >
  cornerBottomShape?: ResponsiveValue<Property.CornerBottomShape | undefined>
  cornerInlineEndShape?: ResponsiveValue<
    Property.CornerInlineEndShape | undefined
  >
  cornerInlineStartShape?: ResponsiveValue<
    Property.CornerInlineStartShape | undefined
  >
  cornerLeftShape?: ResponsiveValue<Property.CornerLeftShape | undefined>
  cornerRightShape?: ResponsiveValue<Property.CornerRightShape | undefined>
  cornerShape?: ResponsiveValue<Property.CornerShape | undefined>
  cornerTopShape?: ResponsiveValue<Property.CornerTopShape | undefined>
  flex?: ResponsiveValue<Property.Flex | undefined>
  flexFlow?: ResponsiveValue<Property.FlexFlow | undefined>
  font?: ResponsiveValue<Property.Font | undefined>
  gap?: ResponsiveValue<Property.Gap | undefined>
  grid?: ResponsiveValue<Property.Grid | undefined>
  gridArea?: ResponsiveValue<Property.GridArea | undefined>
  gridColumn?: ResponsiveValue<Property.GridColumn | undefined>
  gridGap?: ResponsiveValue<Property.GridGap | undefined>
  gridRow?: ResponsiveValue<Property.GridRow | undefined>
  gridTemplate?: ResponsiveValue<Property.GridTemplate | undefined>
  inset?: ResponsiveValue<Property.Inset | undefined>
  insetBlock?: ResponsiveValue<Property.InsetBlock | undefined>
  insetInline?: ResponsiveValue<Property.InsetInline | undefined>
  interestDelay?: ResponsiveValue<Property.InterestDelay | undefined>
  listStyle?: ResponsiveValue<Property.ListStyle | undefined>
  margin?: ResponsiveValue<Property.Margin | undefined>
  marginBlock?: ResponsiveValue<Property.MarginBlock | undefined>
  marginInline?: ResponsiveValue<Property.MarginInline | undefined>
  mask?: ResponsiveValue<Property.Mask | undefined>
  maskBorder?: ResponsiveValue<Property.MaskBorder | undefined>
  offset?: ResponsiveValue<Property.Offset | undefined>
  outline?: ResponsiveValue<Property.Outline | undefined>
  overflow?: ResponsiveValue<Property.Overflow | undefined>
  overscrollBehavior?: ResponsiveValue<Property.OverscrollBehavior | undefined>
  padding?: ResponsiveValue<Property.Padding | undefined>
  paddingBlock?: ResponsiveValue<Property.PaddingBlock | undefined>
  paddingInline?: ResponsiveValue<Property.PaddingInline | undefined>
  placeContent?: ResponsiveValue<Property.PlaceContent | undefined>
  placeItems?: ResponsiveValue<Property.PlaceItems | undefined>
  placeSelf?: ResponsiveValue<Property.PlaceSelf | undefined>
  positionTry?: ResponsiveValue<Property.PositionTry | undefined>
  scrollMargin?: ResponsiveValue<Property.ScrollMargin | undefined>
  scrollMarginBlock?: ResponsiveValue<Property.ScrollMarginBlock | undefined>
  scrollMarginInline?: ResponsiveValue<Property.ScrollMarginInline | undefined>
  scrollPadding?: ResponsiveValue<Property.ScrollPadding | undefined>
  scrollPaddingBlock?: ResponsiveValue<Property.ScrollPaddingBlock | undefined>
  scrollPaddingInline?: ResponsiveValue<
    Property.ScrollPaddingInline | undefined
  >
  scrollTimeline?: ResponsiveValue<Property.ScrollTimeline | undefined>
  textDecoration?: ResponsiveValue<Property.TextDecoration | undefined>
  textEmphasis?: ResponsiveValue<Property.TextEmphasis | undefined>
  textWrap?: ResponsiveValue<Property.TextWrap | undefined>
  timelineTrigger?: ResponsiveValue<Property.TimelineTrigger | undefined>
  timelineTriggerActiveRange?: ResponsiveValue<
    Property.TimelineTriggerActiveRange | undefined
  >
  transition?: ResponsiveValue<Property.Transition | undefined>
  viewTimeline?: ResponsiveValue<Property.ViewTimeline | undefined>
  msAccelerator?: ResponsiveValue<Property.MsAccelerator | undefined>
  msBlockProgression?: ResponsiveValue<Property.MsBlockProgression | undefined>
  msContentZoomChaining?: ResponsiveValue<
    Property.MsContentZoomChaining | undefined
  >
  msContentZoomLimitMax?: ResponsiveValue<
    Property.MsContentZoomLimitMax | undefined
  >
  msContentZoomLimitMin?: ResponsiveValue<
    Property.MsContentZoomLimitMin | undefined
  >
  msContentZoomSnapPoints?: ResponsiveValue<
    Property.MsContentZoomSnapPoints | undefined
  >
  msContentZoomSnapType?: ResponsiveValue<
    Property.MsContentZoomSnapType | undefined
  >
  msContentZooming?: ResponsiveValue<Property.MsContentZooming | undefined>
  msFilter?: ResponsiveValue<Property.MsFilter | undefined>
  msFlowFrom?: ResponsiveValue<Property.MsFlowFrom | undefined>
  msFlowInto?: ResponsiveValue<Property.MsFlowInto | undefined>
  msGridColumns?: ResponsiveValue<Property.MsGridColumns | undefined>
  msGridRows?: ResponsiveValue<Property.MsGridRows | undefined>
  msHighContrastAdjust?: ResponsiveValue<
    Property.MsHighContrastAdjust | undefined
  >
  msHyphenateLimitChars?: ResponsiveValue<
    Property.MsHyphenateLimitChars | undefined
  >
  msHyphenateLimitLines?: ResponsiveValue<
    Property.MsHyphenateLimitLines | undefined
  >
  msHyphenateLimitZone?: ResponsiveValue<
    Property.MsHyphenateLimitZone | undefined
  >
  msImeAlign?: ResponsiveValue<Property.MsImeAlign | undefined>
  msOverflowStyle?: ResponsiveValue<Property.MsOverflowStyle | undefined>
  msScrollChaining?: ResponsiveValue<Property.MsScrollChaining | undefined>
  msScrollLimitXMax?: ResponsiveValue<Property.MsScrollLimitXMax | undefined>
  msScrollLimitXMin?: ResponsiveValue<Property.MsScrollLimitXMin | undefined>
  msScrollLimitYMax?: ResponsiveValue<Property.MsScrollLimitYMax | undefined>
  msScrollLimitYMin?: ResponsiveValue<Property.MsScrollLimitYMin | undefined>
  msScrollRails?: ResponsiveValue<Property.MsScrollRails | undefined>
  msScrollSnapPointsX?: ResponsiveValue<
    Property.MsScrollSnapPointsX | undefined
  >
  msScrollSnapPointsY?: ResponsiveValue<
    Property.MsScrollSnapPointsY | undefined
  >
  msScrollSnapType?: ResponsiveValue<Property.MsScrollSnapType | undefined>
  msScrollTranslation?: ResponsiveValue<
    Property.MsScrollTranslation | undefined
  >
  msScrollbar3dlightColor?: ResponsiveValue<
    Property.MsScrollbar3dlightColor | undefined
  >
  msScrollbarArrowColor?: ResponsiveValue<
    Property.MsScrollbarArrowColor | undefined
  >
  msScrollbarBaseColor?: ResponsiveValue<
    Property.MsScrollbarBaseColor | undefined
  >
  msScrollbarDarkshadowColor?: ResponsiveValue<
    Property.MsScrollbarDarkshadowColor | undefined
  >
  msScrollbarFaceColor?: ResponsiveValue<
    Property.MsScrollbarFaceColor | undefined
  >
  msScrollbarHighlightColor?: ResponsiveValue<
    Property.MsScrollbarHighlightColor | undefined
  >
  msScrollbarShadowColor?: ResponsiveValue<
    Property.MsScrollbarShadowColor | undefined
  >
  msScrollbarTrackColor?: ResponsiveValue<
    Property.MsScrollbarTrackColor | undefined
  >
  msTextAutospace?: ResponsiveValue<Property.MsTextAutospace | undefined>
  msTouchSelect?: ResponsiveValue<Property.MsTouchSelect | undefined>
  msUserSelect?: ResponsiveValue<Property.MsUserSelect | undefined>
  msWrapFlow?: ResponsiveValue<Property.MsWrapFlow | undefined>
  msWrapMargin?: ResponsiveValue<Property.MsWrapMargin | undefined>
  msWrapThrough?: ResponsiveValue<Property.MsWrapThrough | undefined>
  MozAppearance?: ResponsiveValue<Property.MozAppearance | undefined>
  MozBinding?: ResponsiveValue<Property.MozBinding | undefined>
  MozBorderBottomColors?: ResponsiveValue<
    Property.MozBorderBottomColors | undefined
  >
  MozBorderLeftColors?: ResponsiveValue<
    Property.MozBorderLeftColors | undefined
  >
  MozBorderRightColors?: ResponsiveValue<
    Property.MozBorderRightColors | undefined
  >
  MozBorderTopColors?: ResponsiveValue<Property.MozBorderTopColors | undefined>
  MozContextProperties?: ResponsiveValue<
    Property.MozContextProperties | undefined
  >
  MozFloatEdge?: ResponsiveValue<Property.MozFloatEdge | undefined>
  MozForceBrokenImageIcon?: ResponsiveValue<
    Property.MozForceBrokenImageIcon | undefined
  >
  MozOrient?: ResponsiveValue<Property.MozOrient | undefined>
  MozOutlineRadiusBottomleft?: ResponsiveValue<
    Property.MozOutlineRadiusBottomleft | undefined
  >
  MozOutlineRadiusBottomright?: ResponsiveValue<
    Property.MozOutlineRadiusBottomright | undefined
  >
  MozOutlineRadiusTopleft?: ResponsiveValue<
    Property.MozOutlineRadiusTopleft | undefined
  >
  MozOutlineRadiusTopright?: ResponsiveValue<
    Property.MozOutlineRadiusTopright | undefined
  >
  MozStackSizing?: ResponsiveValue<Property.MozStackSizing | undefined>
  MozTextBlink?: ResponsiveValue<Property.MozTextBlink | undefined>
  MozUserFocus?: ResponsiveValue<Property.MozUserFocus | undefined>
  MozUserInput?: ResponsiveValue<Property.MozUserInput | undefined>
  MozUserModify?: ResponsiveValue<Property.MozUserModify | undefined>
  MozWindowDragging?: ResponsiveValue<Property.MozWindowDragging | undefined>
  MozWindowShadow?: ResponsiveValue<Property.MozWindowShadow | undefined>
  WebkitAppearance?: ResponsiveValue<Property.WebkitAppearance | undefined>
  WebkitBorderAfterColor?: ResponsiveValue<
    Property.WebkitBorderAfterColor | undefined
  >
  WebkitBorderAfterStyle?: ResponsiveValue<
    Property.WebkitBorderAfterStyle | undefined
  >
  WebkitBorderAfterWidth?: ResponsiveValue<
    Property.WebkitBorderAfterWidth | undefined
  >
  WebkitBorderBeforeColor?: ResponsiveValue<
    Property.WebkitBorderBeforeColor | undefined
  >
  WebkitBorderBeforeStyle?: ResponsiveValue<
    Property.WebkitBorderBeforeStyle | undefined
  >
  WebkitBorderBeforeWidth?: ResponsiveValue<
    Property.WebkitBorderBeforeWidth | undefined
  >
  WebkitBorderEndColor?: ResponsiveValue<
    Property.WebkitBorderEndColor | undefined
  >
  WebkitBorderEndStyle?: ResponsiveValue<
    Property.WebkitBorderEndStyle | undefined
  >
  WebkitBorderEndWidth?: ResponsiveValue<
    Property.WebkitBorderEndWidth | undefined
  >
  WebkitBorderStartColor?: ResponsiveValue<
    Property.WebkitBorderStartColor | undefined
  >
  WebkitBorderStartStyle?: ResponsiveValue<
    Property.WebkitBorderStartStyle | undefined
  >
  WebkitBorderStartWidth?: ResponsiveValue<
    Property.WebkitBorderStartWidth | undefined
  >
  WebkitBoxReflect?: ResponsiveValue<Property.WebkitBoxReflect | undefined>
  WebkitLineClamp?: ResponsiveValue<Property.WebkitLineClamp | undefined>
  WebkitMaskAttachment?: ResponsiveValue<
    Property.WebkitMaskAttachment | undefined
  >
  WebkitMaskClip?: ResponsiveValue<Property.WebkitMaskClip | undefined>
  WebkitMaskComposite?: ResponsiveValue<
    Property.WebkitMaskComposite | undefined
  >
  WebkitMaskImage?: ResponsiveValue<Property.WebkitMaskImage | undefined>
  WebkitMaskOrigin?: ResponsiveValue<Property.WebkitMaskOrigin | undefined>
  WebkitMaskPosition?: ResponsiveValue<Property.WebkitMaskPosition | undefined>
  WebkitMaskPositionX?: ResponsiveValue<
    Property.WebkitMaskPositionX | undefined
  >
  WebkitMaskPositionY?: ResponsiveValue<
    Property.WebkitMaskPositionY | undefined
  >
  WebkitMaskRepeat?: ResponsiveValue<Property.WebkitMaskRepeat | undefined>
  WebkitMaskRepeatX?: ResponsiveValue<Property.WebkitMaskRepeatX | undefined>
  WebkitMaskRepeatY?: ResponsiveValue<Property.WebkitMaskRepeatY | undefined>
  WebkitMaskSize?: ResponsiveValue<Property.WebkitMaskSize | undefined>
  WebkitOverflowScrolling?: ResponsiveValue<
    Property.WebkitOverflowScrolling | undefined
  >
  WebkitTapHighlightColor?: ResponsiveValue<
    Property.WebkitTapHighlightColor | undefined
  >
  WebkitTextFillColor?: ResponsiveValue<
    Property.WebkitTextFillColor | undefined
  >
  WebkitTextStrokeColor?: ResponsiveValue<
    Property.WebkitTextStrokeColor | undefined
  >
  WebkitTextStrokeWidth?: ResponsiveValue<
    Property.WebkitTextStrokeWidth | undefined
  >
  WebkitTouchCallout?: ResponsiveValue<Property.WebkitTouchCallout | undefined>
  WebkitUserModify?: ResponsiveValue<Property.WebkitUserModify | undefined>
  WebkitUserSelect?: ResponsiveValue<Property.WebkitUserSelect | undefined>
  msContentZoomLimit?: ResponsiveValue<Property.MsContentZoomLimit | undefined>
  msContentZoomSnap?: ResponsiveValue<Property.MsContentZoomSnap | undefined>
  msScrollLimit?: ResponsiveValue<Property.MsScrollLimit | undefined>
  msScrollSnapX?: ResponsiveValue<Property.MsScrollSnapX | undefined>
  msScrollSnapY?: ResponsiveValue<Property.MsScrollSnapY | undefined>
  MozOutlineRadius?: ResponsiveValue<Property.MozOutlineRadius | undefined>
  WebkitBorderAfter?: ResponsiveValue<Property.WebkitBorderAfter | undefined>
  WebkitBorderBefore?: ResponsiveValue<Property.WebkitBorderBefore | undefined>
  WebkitBorderEnd?: ResponsiveValue<Property.WebkitBorderEnd | undefined>
  WebkitBorderStart?: ResponsiveValue<Property.WebkitBorderStart | undefined>
  WebkitMask?: ResponsiveValue<Property.WebkitMask | undefined>
  WebkitTextStroke?: ResponsiveValue<Property.WebkitTextStroke | undefined>
}
