import { RuleTester } from '@typescript-eslint/rule-tester'
import { describe } from 'bun:test'

import { styleOrderRange } from '../index'

const filename = 'src/order-gaps.tsx'

describe('styleOrder compat gaps', () => {
  const tester = new RuleTester({
    languageOptions: {
      ecmaVersion: 'latest',
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
  })
  tester.run('consumed objects and deferred build proof', styleOrderRange, {
    valid: [
      'import { css } from "@devup-ui/react"; import { ORDER } from "./tokens"; function double(n) { const result = n * 2; return result; } css({ styleOrder: double(ORDER) });',
      'import { css } from "@devup-ui/react"; import { ORDER } from "./tokens"; const double = (n) => n * 2; css({ styleOrder: double(ORDER) });',
      'import { css } from "@devup-ui/react"; css(false || { styleOrder: 1 }); css(null ?? { styleOrder: 2 });',
      'import { css, globalCss } from "@devup-ui/react"; css({ "style-order": 2 }); globalCss({ "style-order": 1, body: { "style-order": 254 } });',
      'import { Box } from "@devup-ui/react"; <Box style-order={0} />;',
      'import { css } from "@devup-ui/react"; css({ selectors: { "style-order": { color: "red" } }, props: { "style-order": 0 } });',
      'import * as sx from "@stylexjs/stylex"; sx.create({ "style-order": { color: "red" } }); sx.defineVars({ "style-order": 0 });',
      'import { css } from "@devup-ui/react"; const order = function(n) { return n ** 3; }; css({ styleOrder: order(2) });',
      'import { ClassNames } from "@emotion/react"; <ClassNames>{({ css: c }) => c({ styleOrder: on ? 1 : 2 })}</ClassNames>;',
      'import { ClassNames as CN } from "@emotion/react"; <CN>{({ cx }) => cx({ styleOrder: 0 })}</CN>;',
      'import { ClassNames } from "other"; <ClassNames>{({ css }) => css({ styleOrder: 0 })}</ClassNames>;',
      'import { ClassNames } from "@emotion/react"; <ClassNames>{({ css }) => { function f(css) { return css({ styleOrder: 0 }); } return css({ styleOrder: 1 }); }}</ClassNames>;',
      'import { ClassNames } from "@emotion/react"; function f(ClassNames) { return <ClassNames>{({ css }) => css({ styleOrder: 0 })}</ClassNames>; }',
      'import { ClassNames } from "@emotion/react"; <ClassNames children={({ css }) => css({ styleOrder: 0 })} />;',
      'function f({ css }) { return css({ styleOrder: 0 }); }',
      'import * as C from "@devup-ui/react/compat"; <C.ClassNames>{(helpers) => helpers.css({ styleOrder: 0 })}</C.ClassNames>;',
      'import { css } from "@devup-ui/react"; const parts = [null, { styleOrder: 1 }]; css(...parts); css(...runtime);',
      'import { css } from "@devup-ui/react"; const parts = parts; css(...parts); css(...3);',
      'import { css } from "@devup-ui/react"; css({ selectors: { styleOrder: { color: "red" } }, "@layer": { styleOrder: { color: "blue" } } });',
      'import { css } from "@devup-ui/react"; css({ _media: { styleOrder: { color: "red", styleOrder: 1 } } });',
      'import { css } from "@devup-ui/react"; css({ fontFaces: [{ styleOrder: 0 }] });',
      'import * as sx from "@stylexjs/stylex"; sx.create({ styleOrder: { color: "red" } }); sx.defineVars({ styleOrder: 0 });',
      'import { css, globalCss } from "@devup-ui/react"; import { ORDER } from "./tokens"; css({ styleOrder: ORDER }); globalCss({ body: { styleOrder: ORDER } });',
      'import { css } from "@devup-ui/react"; import * as tokens from "./tokens"; css({ styleOrder: tokens.ORDER }); css({ styleOrder: tokens["ORDER"] });',
      'import { css } from "@devup-ui/react"; import { ORDER } from "./tokens"; const local = ORDER; css({ styleOrder: +local }); css({ styleOrder: `${ORDER}` }); css({ styleOrder: ORDER + 1 }); css({ styleOrder: ORDER || 2 });',
      'import { css } from "@devup-ui/react"; function double(n) { return n * 2; } css({ styleOrder: double(2) });',
      'import { css } from "@devup-ui/react"; const double = (n) => n * 2; const ORDER = double(2); css({ styleOrder: ORDER }); css({ styleOrder: on ? ORDER : 2 });',
      'import { css } from "@devup-ui/react"; function double(n) { const result = n * 2; return result; } css({ styleOrder: double(2) });',
      'import { css } from "@devup-ui/react"; css({ styleOrder: (() => 2)() });',
      'import { css } from "@devup-ui/react"; import { ORDER } from "./tokens"; css({ styleOrder: ORDER ? 1 : 2 }); css({ styleOrder: ORDER ?? 2 });',
      'import { globalCss } from "@devup-ui/react"; import { ORDER } from "./tokens"; globalCss({ styleOrder: ORDER ? 1 : 2 });',
      'import { css } from "@devup-ui/react"; import { ORDER } from "./tokens"; css({ styleOrder: Number(ORDER) }); css({ styleOrder: Math.max(ORDER, 1) }); css({ styleOrder: Math["max"](ORDER, 1) });',
      'import { css } from "@devup-ui/react"; function order(p) { return p.n; } css({ styleOrder: order({ n: 2 }) }); css({ styleOrder: order([2]) });',
      'import styled from "@emotion/styled"; const C = styled.div({ color: "red" }); <C styleOrder={1} />;',
      'import { styled } from "@devup-ui/react"; const C = styled.div`color:red`; <C styleOrder={1} />;',
      'import { styled } from "@devup-ui/react"; const C = C; <C styleOrder={0} />;',
      'import { css } from "@devup-ui/react"; const x = x; css({ styleOrder: on ? 1 : 2 });',
    ].map((code) => ({ filename, code })),
    invalid: [
      ...[
        'import { css } from "@devup-ui/react"; function order() { return 2; } order = runtime; css({ styleOrder: order() });',
        'import { css } from "@devup-ui/react"; function order(n) { return 2; } css({ styleOrder: order(runtime) });',
        ...['0', 'false', '"01"'].map(
          (value) =>
            `import { css } from "@devup-ui/react"; import { ORDER } from "./tokens"; const order = (n) => ${value}; css({ styleOrder: order(ORDER) });`,
        ),
        ...['0', 'false', '"01"', 'null', 'undefined', '255', '1.5'].flatMap(
          (value) => [
            `import { css } from "@devup-ui/react"; function order() { return ${value}; } css({ styleOrder: order() });`,
            `import { globalCss } from "@devup-ui/react"; const order = () => ${value}; globalCss({ body: { styleOrder: order() } });`,
          ],
        ),
        'import { css } from "@devup-ui/react"; function double(n) { return n * 2; } css({ styleOrder: double(0) });',
        'import { css } from "@devup-ui/react"; function order(n) { const result = n * 2; return result; } css({ styleOrder: order(128) });',
        'import { css } from "@devup-ui/react"; css({ "style-order": 0 });',
        'import { globalCss } from "@devup-ui/react"; globalCss({ body: { "style-order": "01" } });',
        'import { ClassNames } from "@emotion/react"; <ClassNames>{({ css }) => css({ styleOrder: 0 })}</ClassNames>;',
        'import { ClassNames as CN } from "@emotion/react"; <CN>{({ css: c }) => c({ styleOrder: 0 })}</CN>;',
        'import * as C from "@devup-ui/react/compat"; <C.ClassNames>{function ({ css }) { return css({ styleOrder: 0 }); }}</C.ClassNames>;',
        'import * as E from "@emotion/react"; <E.ClassNames>{({ css }) => css({ styleOrder: false })}</E.ClassNames>;',
        'import { css } from "@devup-ui/react"; const parts = [{ styleOrder: 0 }]; css(...parts);',
        'import { css } from "@devup-ui/react"; const parts = [[{ styleOrder: 0 }]]; css(...[...[...parts]]);',
        'import { Box } from "@devup-ui/react"; import { jsx } from "react/jsx-runtime"; const args = [Box, { styleOrder: 0 }]; jsx(...args);',
        'import styled from "styled-components"; styled(...["div", { styleOrder: 0 }]);',
        'import * as D from "@devup-ui/react"; D.css({ selectors: { styleOrder: { styleOrder: 0 } } });',
        'import { css } from "@devup-ui/react"; css({ "@layer": { styleOrder: { styleOrder: 0 } } });',
        'import * as C from "@devup-ui/react/compat"; C.createGlobalStyle({ body: { styleOrder: 0 } });',
        'import styled from "@emotion/styled"; const C = styled.div({ color: "red" }); <C styleOrder={0} />;',
        'import { styled } from "@devup-ui/react"; const C = styled.div`color:red`; <C styleOrder={0} />;',
        'import { css } from "@devup-ui/react"; import { ORDER } from "./tokens"; function f(ORDER) { css({ styleOrder: ORDER }); }',
        'import { css } from "@devup-ui/react"; import { order } from "./tokens"; css({ styleOrder: order() });',
        'import { css } from "@devup-ui/react"; function double(n) { return n * 2; } function C(n) { css({ styleOrder: double(n) }); }',
        'import { css } from "@devup-ui/react"; function order() { return runtime; } css({ styleOrder: order() });',
        'import { css } from "@devup-ui/react"; function order() { return order(); } css({ styleOrder: order() });',
        'import { css } from "@devup-ui/react"; const result = result; css({ styleOrder: result });',
        'import { css } from "@devup-ui/react"; const fn = fn; css({ styleOrder: fn() });',
        'import { css } from "@devup-ui/react"; function order() { let result = 2; return result; } css({ styleOrder: order() });',
        'import { css } from "@devup-ui/react"; const order = async () => 2; css({ styleOrder: order() });',
        'import { css } from "@devup-ui/react"; function* order() { return 2; } css({ styleOrder: order() });',
        'import { css } from "@devup-ui/react"; function order({ n }) { return n; } css({ styleOrder: order(2) });',
        'import { css } from "@devup-ui/react"; function order(n) { return n; } css({ styleOrder: order() });',
        'import { css } from "@devup-ui/react"; function order() { return; } css({ styleOrder: order() });',
        'import { css } from "@devup-ui/react"; import { ORDER } from "./tokens"; css({ styleOrder: ORDER ** 2 });',
        'import { css } from "@devup-ui/react"; import { ORDER } from "./tokens"; css({ styleOrder: delete ORDER.x });',
        'import { css } from "@devup-ui/react"; import { ORDER } from "./tokens"; css({ styleOrder: ORDER[runtime] });',
        'import { css } from "@devup-ui/react"; import { ORDER } from "./tokens"; css({ styleOrder: on ? ORDER : 0 });',
        'import { css } from "@devup-ui/react"; import { ORDER } from "./tokens"; ORDER = runtime; css({ styleOrder: ORDER });',
        'import { css } from "@devup-ui/react"; import { ORDER } from "./tokens"; css({ styleOrder: Math[runtime](ORDER) });',
        'import { css } from "@devup-ui/react"; function order(p) { return p.n; } css({ styleOrder: order({ get n() { return 2; } }) });',
        'import { css } from "@devup-ui/react"; function order(p) { return p.n; } css({ styleOrder: order({ n: runtime }) });',
        'import { css } from "@devup-ui/react"; function order(p) { return p.n; } css({ styleOrder: order(new Number(2)) });',
      ].map((code) => ({
        filename,
        code,
        errors: [{ messageId: 'styleOrderRange' }],
      })),
      ...[
        'import { keyframes } from "@devup-ui/react"; keyframes({ from: { "style-order": 1 } });',
        'import * as sx from "@stylexjs/stylex"; sx.create({ a: { "style-order": 1 } });',
        'import { globalCss } from "@devup-ui/react"; globalCss({ fontFaces: [{ "style-order": 1 }] });',
        'import { globalCss } from "@devup-ui/react"; globalCss({ fontFaces: [{ fontFamily: "Example", src: "url(font.woff2)", styleOrder: 2 }] });',
        'import * as D from "@devup-ui/react"; const faces = [{ styleOrder: 0 }]; D.globalCss({ fontFaces: faces });',
        'import * as C from "@devup-ui/react/compat"; <C.Global styles={{ fontFaces: [{ styleOrder: 1 }] }} />;',
        'import { Global } from "@emotion/react"; <Global {...{ styles: { fontFaces: [{ styleOrder: null }] } }} />;',
        'import { Global } from "@emotion/react"; import { jsx } from "react/jsx-runtime"; jsx(Global, { styles: { fontFaces: [{ styleOrder: 1 }] } });',
        'import * as C from "@devup-ui/react/compat"; C.keyframes({ to: { styleOrder: 1 } });',
        'import { keyframes } from "@devup-ui/react"; keyframes(...[{ to: { styleOrder: 1 } }]);',
      ].map((code) => ({
        filename,
        code,
        errors: [{ messageId: 'unsupportedOrder' }],
      })),
    ],
  })
})
