import { RuleTester } from '@typescript-eslint/rule-tester'
import { describe } from 'bun:test'

import cases from '../../../../../../test-fixtures/style-order-w38.json'
import { styleOrderRange } from '../index'

const filename = 'src/style-order.tsx'
const accepted = [
  ...cases.filter((entry) => entry.valid).map((entry) => entry.expression),
  '0x10',
  '0b10',
  '0o10',
  '1_00',
  '2.0',
  '`50`',
  '"\\u0031"',
  '+200',
  'Number("01")',
  'Number(true)',
  'Number(1n)',
  'String(2)',
  '254 - 1',
  '2 * 4',
  '2 ** 3',
  '8 / 2',
  '5 % 3',
  '1 << 2',
  '8 >> 1',
  '-1 >>> 31',
  '1 | 2',
  '3 & 1',
  '3 ^ 1',
  '~(-255)',
  'true ? 2 : 0',
  '(1 === 1) ? 2 : 0',
  '(1 !== 2) ? 2 : 0',
  '(1 < 2) ? 2 : 0',
  '(2 > 1) ? 2 : 0',
  '(1 <= 2) ? 2 : 0',
  '(2 >= 1) ? 2 : 0',
  '("a" < "b") ? 2 : 0',
  '("b" > "a") ? 2 : 0',
  '("a" <= "b") ? 2 : 0',
  '("b" >= "a") ? 2 : 0',
  'false || 2',
  'null ?? 2',
  '2 ?? 0',
  'true && 2',
  '2 || 0',
  '`1${2}`',
  '"1" + 2',
  '2 as number',
  '2 satisfies number',
  'ORDER',
  '({ value: 1 }).value',
  '[2][0]',
  'Math.max(1, 2)',
  'Math.floor(2.5)',
  'Math["max"](1, 2)',
  'on ? 1 : 254',
  'on ? (other ? 2 : 3) : 4',
]
const rejected = [
  ...cases.filter((entry) => !entry.valid).map((entry) => entry.expression),
  '-0',
  'NaN',
  'Infinity',
  '-Infinity',
  '1n',
  '-1n',
  '~1n',
  '"0"',
  '"255"',
  '"1px"',
  '"1.5"',
  '"+1"',
  '"-1"',
  '"0x10"',
  '`1px`',
  '"1" + "px"',
  'Boolean(1)',
  '!false',
  'runtime',
  'on ? 1 : 0',
  'on ? 1 : null',
  'on && 0',
  'false && 2',
  'Number("bad")',
  '+1n',
  '1n + 1n',
  'delete object.x',
  '2 ** 8',
  '2 ** -1',
  '1 == 1',
  '/x/',
  'new Number(1)',
  'unknown(1)',
  'Number()',
  'Number(runtime)',
  'Math.random()',
  'Math.pow(2, 3)',
  '({ value: {} }).value',
  '({ value: null }).value',
  '({ value: true }).value',
  '({ value: undefined }).value',
  '({ value: 1n }).value',
  '({ value: "01" }).value',
  'Symbol.iterator',
  'Math.max',
  '({ get value() { return 1 } }).value',
]

describe('styleOrder value parity', () => {
  const tester = new RuleTester({
    languageOptions: {
      ecmaVersion: 'latest',
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
  })
  const prefix =
    'import { Box, css, styled } from "@devup-ui/react"; const ORDER = 3;'
  tester.run(
    'exact static orders and conditional class orders',
    styleOrderRange,
    {
      valid: accepted.flatMap((value) => [
        { filename, code: `${prefix}<Box styleOrder={${value}} />` },
        { filename, code: `${prefix}css({ styleOrder: ${value} });` },
        { filename, code: `${prefix}styled.div({ styleOrder: ${value} });` },
      ]),
      invalid: rejected.flatMap((value) => [
        {
          filename,
          code: `${prefix}<Box styleOrder={${value}} />`,
          errors: [{ messageId: 'styleOrderRange' }],
        },
        {
          filename,
          code: `${prefix}css({ styleOrder: ${value} });`,
          errors: [{ messageId: 'styleOrderRange' }],
        },
      ]),
    },
  )
})

describe('styleOrder consumed contexts', () => {
  const tester = new RuleTester({
    languageOptions: {
      ecmaVersion: 'latest',
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
  })
  tester.run('API roles, aliases, nesting and lexical scope', styleOrderRange, {
    valid: [
      'import { css } from "other"; css({ styleOrder: 0 });',
      'const css = (x) => x; css({ styleOrder: 0 });',
      'import { css } from "@devup-ui/react"; function f(css) { css({ styleOrder: 0 }); }',
      'import { Box } from "@devup-ui/react"; function f(Box) { return <Box styleOrder={0} />; }',
      'import * as D from "@devup-ui/react"; function f(D) { D.css({ styleOrder: 0 }); return <D.Box styleOrder={0} />; }',
      'import { css } from "@devup-ui/react"; const data = { styleOrder: 0 }; css({ color: fn(data), vars: { styleOrder: 0 }, props: { styleOrder: 0 } });',
      '<div css={{ styleOrder: 0 }} styleOrder={0} />;',
      'import { css } from "@emotion/react"; <Custom css={{ styleOrder: 0 }} />;',
      'import { jsx } from "react/jsx-runtime"; jsx("div", { css: { styleOrder: 0 } });',
      'import { globalCss as g } from "@devup-ui/react"; g({ styleOrder: 1, body: { styleOrder: 2, "@media print": { styleOrder: 3 } } });',
      'import { globalStyle as g } from "@vanilla-extract/css"; g("body", { styleOrder: true ? 2 : 0 });',
      'import { keyframes } from "@devup-ui/react"; keyframes({ from: { vars: { styleOrder: 0 }, opacity: 0 } });',
      'import * as sx from "@stylexjs/stylex"; sx.create({ styleOrder: { color: "red" } }); sx.defineVars({ styleOrder: 0 });',
      'import { styleVariants } from "@vanilla-extract/css"; styleVariants({ styleOrder: { color: "red", styleOrder: 2 } });',
      'import styled from "styled-components"; styled.div.attrs({ styleOrder: 0 }).withConfig({ styleOrder: 0 })({ styleOrder: on ? 1 : 2 });',
      'import { Box, css } from "@devup-ui/react"; <Box props={{ styleOrder: 0 }} onClick={() => css({ styleOrder: 1 })} />;',
      'import { Box } from "@devup-ui/react"; <Box _hover={{ styleOrder: on ? 1 : 2 }} />;',
      'import { css } from "@devup-ui/react"; const c = css; c({ styleOrder: 2 });',
      'import { css } from "@devup-ui/react"; const c = c; css(c);',
      'import { css } from "@devup-ui/react"; css(on && { styleOrder: 2 }); css(on ? { styleOrder: 1 } : { styleOrder: 2 });',
      'import { globalCss } from "@devup-ui/react"; globalCss({ body: true && { styleOrder: 2 } }); globalCss({ body: true ? { styleOrder: 2 } : { styleOrder: 0 } });',
      'import { css } from "@devup-ui/react"; css({ thing: () => ({ styleOrder: 0 }), items: [null, ...[{ styleOrder: 2 }]] });',
      'import * as sx from "@stylexjs/stylex"; sx.create({ a: { color: () => ({ styleOrder: 0 }) } });',
      'import * as sx from "@stylexjs/stylex"; sx.create({ a: () => { const data = { styleOrder: 0 }; return { color: "red" }; } });',
      'import { styleVariants as v } from "@vanilla-extract/css"; const data = { a: { styleOrder: 2 } }; v(data); v();',
      'import { Box } from "@devup-ui/react"; const B = Box; <B styleOrder={2} />;',
      'import D from "@devup-ui/react"; <D.Box styleOrder={2} />;',
      'import { Box } from "@devup-ui/react"; <Box.Box styleOrder={0} />;',
      'import { css } from "other"; <css.Box styleOrder={0} />;',
      '<svg:path styleOrder={0} />;',
    ].map((code) => ({ filename, code })),
    invalid: [
      ...[
        'import { css as c } from "@devup-ui/react"; c({ "styleOrder": 0 });',
        'import * as D from "@devup-ui/react"; D.css({ ["styleOrder"]: 0 });',
        'import { css } from "@devup-ui/react"; const c = css; c({ styleOrder: 0 });',
        'import { css } from "@devup-ui/react"; css(base, { styleOrder: 0 });',
        'import { css } from "@devup-ui/react"; css([{ styleOrder: 0 }]);',
        'import { css } from "@devup-ui/react"; css({ ...{ styleOrder: 0 } });',
        'import { css } from "@emotion/react"; css({ styleOrder: 0 });',
        'import { css } from "@emotion/css"; css({ styleOrder: 0 });',
        'import { style } from "@vanilla-extract/css"; style({ styleOrder: 0 });',
        'import { styleVariants } from "@vanilla-extract/css"; styleVariants({ a: { styleOrder: 0 } });',
        'import styled from "@emotion/styled"; styled("div")({ styleOrder: 0 });',
        'import styled from "styled-components"; styled.div({ _hover: { styleOrder: 0 } });',
        'import { styled } from "@devup-ui/react"; styled("div", { styleOrder: 0 });',
        'import { Box } from "@devup-ui/react"; <Box {...{ styleOrder: 0 }} />;',
        'import { Box } from "@devup-ui/react"; <Box css={{ styleOrder: 0 }} />;',
        'import { Box } from "@devup-ui/react"; <Box selectors={{ "&:hover": { styleOrder: 0 } }} />;',
        'import * as D from "@devup-ui/react"; <D.Box styleOrder={0} />;',
        'import { Box } from "@devup-ui/react"; import { jsx } from "react/jsx-runtime"; jsx(Box, { styleOrder: 0 });',
        'import { Box } from "@devup-ui/react"; import * as R from "react/jsx-runtime"; R.jsxs(Box, { _hover: { styleOrder: 0 } });',
        'import { jsx } from "@emotion/react"; jsx("div", { css: { styleOrder: 0 } });',
        'import { css } from "@emotion/react"; <div css={{ styleOrder: 0 }} />;',
        'import { globalCss } from "@devup-ui/react"; globalCss({ body: { styleOrder: 0 } });',
        'import { css } from "@devup-ui/react"; let ORDER = 1; css({ styleOrder: ORDER });',
        'import { css } from "@devup-ui/react"; const ORDER = 1; ORDER = 2; css({ styleOrder: ORDER });',
        'import { css } from "@devup-ui/react"; const ORDER = ORDER; css({ styleOrder: ORDER });',
        'import { css } from "@devup-ui/react"; function f(undefined) { css({ styleOrder: undefined }); }',
        'import { css } from "@devup-ui/react"; function f(Number) { css({ styleOrder: Number(1) }); }',
        'import { css } from "@devup-ui/react"; function f(Math) { css({ styleOrder: Math.max(1, 2) }); }',
        'import { css } from "@devup-ui/react"; css(on || { styleOrder: 0 });',
        'import { Box } from "@devup-ui/react"; import { jsx } from "react/jsx-runtime"; const props = { styleOrder: 0 }; jsx(Box, props);',
        'import { Box } from "@devup-ui/react"; import { jsx } from "react/jsx-runtime"; jsx(Box, { ...{ styleOrder: 0 } });',
        'import { styleVariants } from "@vanilla-extract/css"; styleVariants({ a: "red" }, (color) => ({ color, styleOrder: 0 }));',
        'import styled from "@emotion/styled"; styled.div(function () { return { styleOrder: 0 }; });',
        'import { Box } from "@devup-ui/react"; <Box css={() => ({ styleOrder: 0 })} />;',
        'import { "css" as c } from "@devup-ui/react"; c({ styleOrder: 0 });',
        'import { css } from "@devup-ui/react"; const objects = { a: 1 }; css({ [objects]: 3, styleOrder: 0 });',
      ].map((code) => ({
        filename,
        code,
        errors: [{ messageId: 'styleOrderRange' }],
      })),
      ...[
        'import { globalCss as g } from "@devup-ui/react"; g({ body: { styleOrder: on ? 1 : 2 } });',
        'import { globalStyle } from "@vanilla-extract/css"; globalStyle("body", { styleOrder: on && 2 });',
        'import { createGlobalStyle } from "styled-components"; createGlobalStyle({ body: { styleOrder: on ? 1 : 2 } });',
        'import { createGlobalStyle } from "@devup-ui/react/compat"; createGlobalStyle({ body: { styleOrder: on ? 1 : 2 } });',
        'import { Global as G } from "@emotion/react"; <G styles={{ body: { styleOrder: on ? 1 : 2 } }} />;',
        'import { globalCss } from "@devup-ui/react"; globalCss({ body: on && { styleOrder: 1 } });',
        'import { globalCss } from "@devup-ui/react"; globalCss(on ? { body: { styleOrder: 1 } } : { body: { color: "red" } });',
      ].map((code) => ({
        filename,
        code,
        errors: [{ messageId: 'globalOrder' }],
      })),
      ...[
        'import { keyframes } from "@devup-ui/react"; keyframes({ styleOrder: 1 });',
        'import { keyframes } from "@emotion/react"; keyframes({ from: { styleOrder: 1 } });',
        'import { keyframes } from "@vanilla-extract/css"; keyframes({ from: { selectors: { "&": { styleOrder: 1 } } } });',
        'import * as sx from "@stylexjs/stylex"; sx.keyframes({ to: { styleOrder: 1 } });',
        'import sx from "@stylexjs/stylex"; sx.create({ a: { styleOrder: 1 } });',
        'import { create as c } from "@stylexjs/stylex"; c({ a: (order) => ({ styleOrder: order }) });',
        'import * as sx from "@stylexjs/stylex"; sx.create({ a: { ":hover": { styleOrder: 1 } } });',
        'import { positionTry } from "@stylexjs/stylex"; positionTry({ styleOrder: 1 });',
        'import { viewTransitionClass } from "@stylexjs/stylex"; viewTransitionClass({ styleOrder: 1 });',
        'import * as sx from "@stylexjs/stylex"; sx.create({ a: function () { return { styleOrder: 1 }; } });',
      ].map((code) => ({
        filename,
        code,
        errors: [{ messageId: 'unsupportedOrder' }],
      })),
      {
        filename,
        code: 'import { Box } from "@devup-ui/react"; <Box styleOrder />;',
        errors: [{ messageId: 'wrongType' }],
      },
      {
        filename,
        code: 'import { css } from "@devup-ui/react"; css({ styleOrder: 0, _hover: { styleOrder: 0 } });',
        errors: [
          { messageId: 'styleOrderRange' },
          { messageId: 'styleOrderRange' },
        ],
      },
    ],
  })
})
