export const importTypeFixtures: readonly {
  readonly code: string
  readonly jsx: boolean
  readonly edges: readonly string[]
}[] = [
  ...[
    "type X = typeof import('./types');",
    "type X = import('./types').T;",
    "export type X = typeof import('./types');",
    "export type X = import('./types').T;",
    "type X = {value: import('./types').T; loader: typeof import('./types')};",
    "type X<T> = T extends import('./types').T ? import('./types').U : never;",
    "type X = import('./types').T | import('./other-types').T;",
    "type X = (value: import('./types').T) => import('./types').U;",
    "type X = `prefix${import('./types').T}`;",
    "interface X {value: import('./types').T; loader: typeof import('./types')}",
    "type X = typeof /* marker */ import /* next */ ('./types');",
    "type X = typeof import('./types')\n",
  ].map((prefix) => ({
    code: `${prefix}\nconst x = typeof import('./real'); require('./required');`,
    jsx: false,
    edges: ['dynamic:./real', 'static:./required'],
  })),
  ...[
    "const x: import('./types').T = import('./real');",
    "const x: typeof import('./types') = typeof import('./real');",
    "let x: Promise<import('./types').T> = import('./real');",
    "const x: T extends U ? import('./types').T : never = import('./real');",
    "const f = (x: () => import('./types').T = () => import('./real')) => import('./body');",
    "const x = import('./real') as {fn: () => import('./types').T};",
    "const x = import('./real') as (() => import('./types').T);",
    "const x = f<import('./types').T>(import('./real'));",
    "function f<T extends import('./types').T>(x = import('./real')) {return import('./body')}",
    "const f = <T extends import('./types').T>(x = import('./real')) => import('./body');",
    "const x = <import('./types').T>import('./real');",
    "const x = a < import('./real');",
    "class C extends mixin({value: import('./real')}) {f() {return import('./body')}}",
    "type X = typeof import('./types')\nimport('./real');",
    "type X = import('./types').T\nimport('./real');",
    "function f(x: import('./types').T = import('./real')) {return import('./body')}",
    "function f(x: import('./types').T = import('./real')): Promise<import('./types').T> {return import('./body')}",
    "const f = (x: import('./types').T = import('./real')): Promise<import('./types').T> => import('./body');",
    "function f({x}: import('./types').T = import('./real')) {return import('./body')}",
    "class C {x: import('./types').T = import('./real'); f(x: import('./types').T) {return import('./body')}}",
    "const x = import('./real') as import('./types').T;",
    "const x = import('./real') satisfies import('./types').T;",
    "const x = {type: typeof import('./real'), value: import('./body')};",
    "const f = (x = typeof import('./real')) => import('./body');",
    "const x = typeof import('./real');",
    "const x = ok ? f() : typeof import('./real');",
    "const x = ok ? f(import('./body')) : import('./real');",
    "const x = ok ? f() : ((x = import('./real')) => x);",
    "const as = (x) => x; const x = as(import('./real'));",
    "const satisfies = (x) => x; const x = satisfies(import('./real'));",
    "const x = {as: typeof import('./real')};",
    "obj.class; const x = {value: import('./real')};",
    "const x = {interface: import('./real'), const: import('./body')};",
    "const x = import('./real') as import('./types').T && import('./body');",
    "const x = import('./real') as number ? import('./body') : null;",
    "const x = ok ? (f()) : import('./real');",
    "const x = ok ? (value) : typeof import('./real');",
    "const x = ok ? ((f(g()))) : import('./real');",
    "const x = ok ? (f(import('./body'))) : import('./real');",
    "const x = ok ? (value) : {loader: import('./real')};",
    "const x = ok ? (value) : (() => import('./real'));",
    "const x = ok ? (value) : (x) => import('./real');",
    "const x = ok ? (value) : other ? (f()) : import('./real');",
    "const x = ok ? (value) : typeof (import('./real'));",
    "const x = ok ? (value) : (x = import('./real')): import('./types').T => x;",
    "const x = ok ? f() : (x = import('./real')): import('./types').T => x;",
    "const x = ok ? (value) : (): {loader: import('./types').T} => ({loader: import('./real')});",
    "const x = {async f(): import('./types').T {return import('./real')}};",
    "class C {async f(): import('./types').T {return import('./real')}}",
    "const x = {async f(x: import('./types').T = import('./real')): Promise<import('./types').T> {return import('./body')}};",
    "class C {static async f(x: import('./types').T = import('./real')): Promise<import('./types').T> {return import('./body')}}",
    "const f = async (x: import('./types').T = import('./real')): Promise<import('./types').T> => import('./body');",
    "async function f(x: import('./types').T = import('./real')): Promise<import('./types').T> {return import('./body')}",
    "function f(): import('./types').T; function f() {return import('./real')}",
  ].map((code) => ({
    code,
    jsx: false,
    edges: code.includes('f(import')
      ? ['dynamic:./body', 'dynamic:./real']
      : code.includes('./body')
        ? ['dynamic:./real', 'dynamic:./body']
        : ['dynamic:./real'],
  })),
  {
    code: "type X = import('./types').T",
    jsx: false,
    edges: [],
  },
  {
    code: "type X = import('./types').T; const x = typeof import('./types');",
    jsx: false,
    edges: ['dynamic:./types'],
  },
  {
    code: "const x: import('./types').T = <div>{typeof import('./real')}import('phantom')</div>;",
    jsx: true,
    edges: ['dynamic:./real'],
  },
  ...[
    "const x = <div>{ok ? (f()) : import('./real')}import('phantom')</div>;",
    "const x = <div>{ok ? (value) : typeof import('./real')}</div>;",
    "const x = <div>{ok ? ((f(g()))) : import('./real')}</div>;",
  ].map((code) => ({ code, jsx: true, edges: ['dynamic:./real'] })),
]
