import { spawnSync } from 'node:child_process'
import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  realpathSync,
  rmSync,
  writeFileSync,
} from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'

import { expect, it } from 'bun:test'

import { discoverTests } from '../../../../test-harness/groups'

it('matches independently executed native files when all supported names and scanner directory boundaries occur', () => {
  // Given: independent corpus, not generated by the harness discoverer.
  const root = realpathSync.native(
    mkdtempSync(join(tmpdir(), 'devup-native-discovery-')),
  )
  const receipt = join(root, 'executed.txt')
  const supported = [
    'js',
    'jsx',
    'ts',
    'tsx',
    'mjs',
    'cjs',
    'mts',
    'cts',
  ] as const
  const suffixes = ['.test', '_test', '.spec', '_spec'] as const
  const expected = [
    ...supported.flatMap((extension) =>
      suffixes.map((suffix) => `packages/corpus/case${suffix}.${extension}`),
    ),
    'packages/x_test.ts',
    'packages/x_spec.cts',
    'packages/dist/generated.test.ts',
    'packages/pkg/generated.spec.js',
  ].sort()
  const ignored = [
    'packages/node_modules/dependency.test.ts',
    'packages/.hidden/hidden.test.ts',
    'packages/corpus/case.test.mjsx',
    'packages/corpus/case.test.cjsx',
    'packages/corpus/case.test.mtsx',
    'packages/corpus/case.test.ctsx',
    'packages/corpus/case_test_extra.ts',
    'packages/corpus/case_spec_extra.ts',
  ] as const
  try {
    writeFileSync(join(root, 'bunfig.toml'), '[test]\nroot="packages"\n')
    for (const file of [...expected, ...ignored]) {
      const path = join(root, file)
      mkdirSync(dirname(path), { recursive: true })
      writeFileSync(
        path,
        `import {it,expect} from 'bun:test';import {appendFileSync} from 'node:fs';it(${JSON.stringify(file)},()=>{appendFileSync(${JSON.stringify(receipt)},${JSON.stringify(`${file}\n`)});expect(1).toBe(1)})`,
      )
    }
    // When: actual native automatic discovery, without explicit file arguments.
    const native = spawnSync(
      process.execPath,
      [`--config=${join(root, 'bunfig.toml')}`, 'test'],
      {
        cwd: root,
        encoding: 'utf8',
      },
    )
    if (native.error) throw native.error
    const executed = readFileSync(receipt, 'utf8').trim().split(/\r?\n/).sort()
    console.info(
      JSON.stringify({
        case: 'native-discovery-parity',
        native: native.stdout + native.stderr,
        executed,
      }),
    )
    // Then: positive native receipt and independent harness/native parity.
    expect(native.status).toBe(0)
    expect(executed).toEqual(expected)
    expect(discoverTests(root)).toEqual(executed)
  } finally {
    rmSync(root, { recursive: true, force: true })
  }
})
