export const oracleScannerFixtures: readonly {
  readonly code: string
  readonly loader: 'js' | 'jsx' | 'ts' | 'tsx'
  readonly edges: readonly string[]
}[] = [
  ...[
    "const x = a < import('./real') > (b);",
    "const x = a < import('./real') > b;",
    "const x = a < import('./real') > (import('./body'));",
    "const x = a < import('./real') > (b) / 2;",
    "const x = a < import('./real') > (b); const node = <div>import('phantom'){require('./required')}</div>;",
  ].map((code) => ({
    code,
    loader: code.includes('<div>') ? ('jsx' as const) : ('js' as const),
    edges: code.includes('./required')
      ? ['dynamic:./real', 'static:./required']
      : code.includes('./body')
        ? ['dynamic:./real', 'dynamic:./body']
        : ['dynamic:./real'],
  })),
  ...[
    "type X = string\nfoo(import('./real'));",
    "type X = string\nvoid import('./real');",
    "type X = string\n(() => import('./real'))();",
    "type X = import('./types').T\nfoo(import('./real'));",
    "type X = {x: import('./types').T}\n(() => import('./real'))();",
    "type X = string /* newline\n */ foo(import('./real'));",
    "type X =\n import('./types').T\n | import('./types').U\nfoo(import('./real'));",
    "type X = T\n & import('./types').T\nvoid import('./real');",
    "type X = import('./types').T\n['x']\nfoo(import('./real'));",
    "type X<T> = T extends\n import('./types').T\n ? import('./types').U\n : import('./types').V\nfoo(import('./real'));",
    "type X = (x: import('./types').T)\n => import('./types').U\nfoo(import('./real'));",
    "type X = <T extends import('./types').T>\n(x: T) => import('./types').U\nfoo(import('./real'));",
    "type X = typeof import('./types')\nfoo(import('./real'));",
    "type X = keyof\n import('./types').T\nvoid import('./real');",
    "type X = new\n(x: import('./types').T) => import('./types').U\nfoo(import('./real'));",
    "let x: import('./types').T\nfoo(import('./real'));",
    "const x = value as import('./types').T\nvoid import('./real');",
    "const x = foo! as import('./types').T; import('./real');",
    "const x = foo! satisfies import('./types').T; import('./real');",
    "const x = import('./real')! as import('./types').T;",
    "const x = import('./real')! satisfies import('./types').T;",
    "const x = !import('./real') as import('./types').T;",
    "const x = 'text' as import('./types').T; import('./real');",
    "const x = {} satisfies import('./types').T; import('./real');",
    "const x = foo! / import('./real');",
    "const x = !import('./real');",
    "const x = import('./real') as import('./types').T;",
    "declare function f<T>(): import('./types').T; import('./real');",
    "declare function f<T extends import('./types').T>(): import('./types').T; import('./real');",
    "declare function f<T extends Array<import('./types').T>>(x: import('./types').T): import('./types').T; import('./real');",
    "declare function f<T>(): import('./types').T\nimport('./real');",
    "function f<T>(): import('./types').T; function f() {return import('./real')}",
    "function f<T>(x: import('./types').T = import('./real')): import('./types').T {return import('./body')}",
    "const f = <T extends import('./types').T>(x = import('./real')): import('./types').T => import('./body');",
    "const x = f<import('./types').T>(import('./real'));",
    "const x = ok ? (f<T>()) : import('./real');",
    "const x = a < import('./real') > b;",
    "const x = <import('./types').T>import('./real');",
    "const x = <number>value / import('./real');",
  ].map((code) => ({
    code,
    loader: 'ts' as const,
    edges: code.includes('./body')
      ? ['dynamic:./real', 'dynamic:./body']
      : ['dynamic:./real'],
  })),
  ...[
    "const x = foo! as import('./types').T;",
    "const x = foo! satisfies import('./types').T;",
    "declare function f<T>(): import('./types').T;",
    "declare function f<T extends Array<import('./types').T>>(): import('./types').T;",
    "declare function f<T>(): import('./types').T",
    "const x = a < import('./types') > (b);",
    "import { type as } from './types';",
    "export { type as } from './types';",
    "import { type as as as } from './types';",
    "export { type as as as } from './types';",
    "import { type as as renamed } from './types';",
    "export { type as as renamed } from './types';",
    "import {type A, type as,} from './types';",
    "export {type as as 'renamed'} from './types';",
  ].map((code) => ({ code, loader: 'ts' as const, edges: [] })),
  ...[
    "async function f(){for await(const x of xs) /import('phantom')/.test(x); import('./real');}",
    "async function f(){for /*marker*/ await /*next*/ (const x of xs) /require('phantom')/.test(x); import('./real');}",
    "async function f(){for //marker\n await (const x of xs) /import('phantom')/.test(x); import('./real');}",
    "async function f(){for await(const x of xs) import('./real');}",
    "async function f(){for await(const x of xs) {import('./real');} /import('phantom')/.test(xs);}",
    "async function f(){const x = await value / import('./real');}",
    "async function f(){const x = await (value) / import('./real');}",
    "async function f(){for(const x of xs) /import('phantom')/.test(x); import('./real');}",
    "async function f(){for await(const x of import('./real')) /import('phantom')/.test(x);}",
    "async function f(){for await(const x of xs) constCall(import('./real'));}",
  ].map((code) => ({ code, loader: 'js' as const, edges: ['dynamic:./real'] })),
  ...[
    "import {type as renamed} from './required';",
    "export {type as renamed} from './required';",
    "import {type as as} from './required';",
    "export {type as as} from './required';",
    "import {type} from './required';",
    "import {from} from './required';",
    "import {'type' as renamed} from './required';",
    "export {type as 'as'} from './required';",
    "import {type A, type as renamed} from './required';",
    "export {type as, value} from './required';",
  ].map((code) => ({
    code,
    loader: 'ts' as const,
    edges: ['static:./required'],
  })),
  {
    code: "const f = <T extends import('./types').T>(x = import('./real')) => <div>import('phantom'){require('./required')}</div>;",
    loader: 'tsx',
    edges: ['dynamic:./real', 'static:./required'],
  },
  {
    code: "const x = `import('phantom') ${<div>import('phantom'){import('./real')}</div>}`; import(name); require('./' + name);",
    loader: 'jsx',
    edges: ['dynamic:./real'],
  },
]
