import { glob, readFile, writeFile } from 'node:fs/promises'

const files = await glob('src/**/*.mdx')

const q = []
for await (const file of files) {
  q.push(
    readFile(file, {
      encoding: 'utf-8',
    }).then((content) => {
      const titleIndex = content.toString().indexOf('#')
      if (content.trim().length === 0 || titleIndex === -1) {
        return null
      }
      const fileName = file.split(/[/\\]/).pop()

      return {
        text: content.toString().substring(titleIndex),
        title: /(#)+ (.*)/.exec(content.toString())[1],
        url: file
          .replace(/src[/\\]app[/\\]\(detail\)[/\\]/, '')
          .replace(fileName, ''),
      }
    }),
  )
}

const res = await Promise.all(q)

await writeFile('public/search.json', JSON.stringify(res))

// Demo barrel.
//
// The component docs render every file under `<component>/demo/`. Discovering
// them at runtime (`readdir` + computed `import()`) or through a bundler
// specific helper (`import.meta.glob`) hides those edges from static import
// analysis, and only one of the two bundlers understands each form. Emitting
// explicit imports keeps the demo graph visible to BOTH Turbopack and Vite, so
// the Next and vinext builds extract styles from exactly the same file set.
const demoFiles = []
for await (const file of glob('src/app/**/demo/*.tsx')) {
  demoFiles.push(file.split(/[/\\]/).join('/'))
}

const demos = demoFiles
  .map((file) => {
    const segments = file.split('/')
    const filename = segments.at(-1)

    return {
      // `src/utils/demos.generated.ts` -> demo module, extension dropped so
      // both bundlers resolve it through their standard extension list.
      specifier: `../${segments.slice(1, -1).join('/')}/${filename.replace(/\.tsx$/, '')}`,
      // Label consumed by `getDemos`: `<component>/demo/<filename>`.
      label: `${segments.at(-3)}/demo/${filename}`,
    }
  })
  .sort((left, right) => left.specifier.localeCompare(right.specifier))

await writeFile(
  'src/utils/demos.generated.ts',
  [
    '// AUTO-GENERATED by apps/landing/script.js - do not edit by hand.',
    '// Run `node ./script.js` (part of `dev`, `build` and `build:next`) to refresh.',
    "import type { ComponentType } from 'react'",
    '',
    ...demos.map(
      ({ specifier }, index) => `import demo${index} from '${specifier}'`,
    ),
    '',
    'export const DEMOS: readonly (readonly [string, ComponentType])[] = [',
    ...demos.map(({ label }, index) => `  ['${label}', demo${index}],`),
    ']',
    '',
  ].join('\n'),
)
