use serial_test::serial;

use super::super::retained_css::{CSS, ENTRY};
use crate::{ExtractOption, ExtractOutput, ResolvedModule};

fn extract_helper(helper: &str) -> Result<ExtractOutput, Box<dyn std::error::Error>> {
    let helper = helper.to_string();
    let resolver = move |specifier: &str, importer: &str| match (specifier, importer) {
        ("./helper", "/src/card.css.ts") => Some(ResolvedModule {
            path: "/src/helper.ts".to_string(),
            code: helper.clone(),
        }),
        ("./styles.module.css", "/src/helper.ts") => Some(ResolvedModule {
            path: "/src/styles.module.css".to_string(),
            code: CSS.to_string(),
        }),
        _ => None,
    };
    crate::extract_with_modules(
        "/src/card.css.ts",
        ENTRY,
        ExtractOption::default(),
        false,
        &resolver,
    )
}

#[rstest::rstest]
#[case("styles.card", "card")]
#[case("styles['card']", "card")]
#[case("styles['']", "")]
#[case("styles[Symbol.toPrimitive]", "Symbol(Symbol.toPrimitive)")]
#[case("styles.valueOf", "valueOf")]
#[case("styles.toString", "toString")]
#[case("String(styles)", "Symbol(Symbol.toPrimitive)")]
#[case("+styles", "Symbol(Symbol.toPrimitive)")]
#[case("styles + ''", "Symbol(Symbol.toPrimitive)")]
#[case("`${styles}`", "Symbol(Symbol.toPrimitive)")]
#[case("'card' in styles", "has:card")]
#[case("Object.keys(styles)", "ownKeys")]
#[case("Reflect.ownKeys(styles)", "ownKeys")]
#[case("(()=>{for(const key in styles){}return 'blue';})()", "ownKeys")]
#[case("({...styles})", "ownKeys")]
#[case("[...styles]", "Symbol(Symbol.iterator)")]
#[case("JSON.stringify(styles)", "toJSON")]
#[case(
    "Object.getOwnPropertyDescriptor(styles,'card')",
    "getOwnPropertyDescriptor:card"
)]
#[case(
    "Reflect.getOwnPropertyDescriptor(styles,'card')",
    "getOwnPropertyDescriptor:card"
)]
#[case("Object.getOwnPropertyDescriptors(styles)", "ownKeys")]
#[case("Object.getPrototypeOf(styles)", "getPrototypeOf")]
#[case("Reflect.getPrototypeOf(styles)", "getPrototypeOf")]
#[case("styles.__proto__", "__proto__")]
#[case(
    "Object.prototype.hasOwnProperty.call(styles,'card')",
    "getOwnPropertyDescriptor:card"
)]
#[case("Reflect.has(styles,'card')", "has:card")]
#[case("Reflect.get(styles,'card')", "card")]
#[case("(()=>{const {card}=styles;return card;})()", "card")]
#[case("styles[(()=> 'card')()]", "card")]
#[serial]
fn css_observation_is_fatal_when_top_level_read_is_caught(
    #[case] observation: &str,
    #[case] key: &str,
    #[values(
        "import styles from './styles.module.css';",
        "import * as styles from './styles.module.css';"
    )]
    import: &str,
) {
    // Given: the fallback is a wrong CSS value, and error mutation cannot erase evidence.
    css::file_map::reset_file_map();
    let helper = format!(
        "{import}\nlet color: string='blue';\ntry{{\n  {observation};\n}}catch(error){{error.message='mutated';error.stack='';color='red';}}\nexport {{color}};"
    );
    // When
    let error = extract_helper(&helper)
        .err()
        .map(|error| error.to_string())
        .unwrap_or_default();
    // Then
    let column = match observation {
        "(()=>{for(const key in styles){}return 'blue';})()" => 9,
        "({...styles})" => 5,
        "[...styles]" => 4,
        "`${styles}`" => 6,
        "(()=>{const {card}=styles;return card;})()" => 16,
        _ => 3,
    };
    assert!(
        error.starts_with(&format!("/src/helper.ts:4:{column}:")),
        "{observation}: {error}"
    );
    assert!(error.contains(&format!("export '{key}'")), "{error}");
    assert!(
        error.contains("/src/styles.module.css") && error.contains("generated by the bundler"),
        "{error}"
    );
    assert_eq!(error.matches("Fix:").count(), 1, "{error}");
    assert!(
        error.contains("className={styles.card}") && error.contains("css()"),
        "{error}"
    );
    assert!(
        !error.contains("mutated") && !error.contains("devup-ui-stylesheet"),
        "{error}"
    );
}

#[rstest::rstest]
#[case("import styles from './styles.module.css';", "styles.card")]
#[case("import * as styles from './styles.module.css';", "styles.card")]
#[case("import {card} from './styles.module.css';", "card")]
#[case("import {card} from './styles.module.css';", "typeof card")]
#[serial]
fn css_observation_keeps_first_site_once_when_called_read_is_caught_repeatedly(
    #[case] import: &str,
    #[case] read: &str,
) {
    // Given
    css::file_map::reset_file_map();
    let helper = format!(
        "{import}\nconst label: string='한글😀';\nfunction read(){{\n  try{{return {read};}}catch(error){{error.message='mutated';return 'red';}}\n}}\nread();export const color=read();"
    );
    // When
    let error = extract_helper(&helper)
        .err()
        .map(|error| error.to_string())
        .unwrap_or_default();
    // Then
    let column = if read == "typeof card" { 21 } else { 14 };
    assert!(
        error.starts_with(&format!("/src/helper.ts:4:{column}:")),
        "{error}"
    );
    assert_eq!(error.matches("JS execution error:").count(), 1, "{error}");
    assert_eq!(error.matches("Fix:").count(), 1, "{error}");
    assert!(
        error.contains("export 'card'") && !error.contains("mutated"),
        "{error}"
    );
}

#[rstest::rstest]
#[case("import styles from './styles.module.css';")]
#[case("import * as styles from './styles.module.css';")]
#[serial]
fn css_observation_allows_known_object_when_typeof_and_passing_do_not_inspect_it(
    #[case] import: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    // Given: passing to both called and uncalled functions must not read properties.
    css::file_map::reset_file_map();
    let helper = format!(
        "{import}\nfunction identity(value){{return value;}}\nfunction neverCalled(value){{return value.card;}}\nconst holder={{styles}};const passed=identity(holder.styles);const thunk=()=>neverCalled(passed);identity(thunk);\nexport const color=typeof passed==='object'?'blue':'red';"
    );
    // When
    let output = extract_helper(&helper)?;
    // Then
    assert!(output.styles.iter().any(
        |style| matches!(style, crate::ExtractStyleValue::Static(value) if value.value() == "blue")
    ));
    assert_eq!(output.dependencies, ["/src/helper.ts"]);
    assert!(output.code.contains("import \"./styles.module.css\";"));
    Ok(())
}

#[test]
#[serial]
fn css_observation_preserves_first_key_when_dynamic_keys_repeat_at_one_site() {
    // Given
    css::file_map::reset_file_map();
    let helper = "import styles from './styles.module.css';\nlet color='blue';\nfor(const key of ['card','other']){\n  try{color=styles[key];}catch(error){error.message='mutated';color='red';}\n}\nexport {color};";
    // When
    let error = extract_helper(helper)
        .err()
        .map(|error| error.to_string())
        .unwrap_or_default();
    // Then
    assert!(error.starts_with("/src/helper.ts:4:13:"), "{error}");
    assert!(
        error.contains("export 'card'") && !error.contains("export 'other'"),
        "{error}"
    );
    assert_eq!(error.matches("JS execution error:").count(), 1, "{error}");
    assert_eq!(error.matches("Fix:").count(), 1, "{error}");
}
