use serial_test::serial;

use super::retained_css::{CSS, ENTRY};
use crate::{ExtractOption, ResolvedModule};

#[path = "css_observations.rs"]
mod observations;

#[path = "css_elision.rs"]
mod elision;

#[rstest::rstest]
#[case("import styles from './styles.module.css';", false)]
#[case("import {card as cardClass} from './styles.module.css';", false)]
#[case("import * as styles from './styles.module.css';", false)]
#[case(
    "import styles, {card as cardClass} from './styles.module.css';import * as namespace from './styles.module.css';",
    false
)]
#[case(
    "import styles from './styles.module.css';function neverCalled(){return styles.card;}",
    true
)]
#[case(
    "import {card} from './styles.module.css';function neverCalled(){return card;}",
    true
)]
#[case(
    "import * as styles from './styles.module.css';function neverCalled(){return styles.card;}",
    true
)]
#[case("import './styles.module.css';", true)]
#[serial]
fn css_retention_follows_default_elision_when_css_bindings_are_unused_or_uncalled(
    #[case] declarations: &str,
    #[case] retained_in_ts: bool,
    #[values("ts", "tsx", "mts", "cts", "js", "jsx", "mjs")] extension: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    // Given
    css::file_map::reset_file_map();
    let helper = format!("{declarations}export const color='red';");
    let helper_path = format!("/src/helper.{extension}");
    let retained = retained_in_ts || matches!(extension, "js" | "jsx" | "mjs" | "cjs");
    let resolver = move |specifier: &str, importer: &str| match (specifier, importer) {
        ("./helper", "/src/card.css.ts") => Some(ResolvedModule {
            path: helper_path.clone(),
            code: helper.clone(),
        }),
        ("./styles.module.css", importer) if importer == helper_path => Some(ResolvedModule {
            path: "/src/styles.module.css".to_string(),
            code: CSS.to_string(),
        }),
        _ => None,
    };
    // When
    let output = crate::extract_with_modules(
        "/src/card.css.ts",
        ENTRY,
        ExtractOption::default(),
        false,
        &resolver,
    )?;
    // Then
    assert_eq!(
        output.code.contains("import \"./styles.module.css\";"),
        retained,
        "{}",
        output.code
    );
    assert_eq!(output.dependencies, [format!("/src/helper.{extension}")]);
    assert!(output.styles.iter().any(
        |style| matches!(style, crate::ExtractStyleValue::Static(value) if value.value() == "red")
    ));
    Ok(())
}

#[rstest::rstest]
#[case("import styles from './styles.module.css';", "styles.card", "card")]
#[case("import styles from './styles.module.css';", "styles", "toJSON")]
#[case(
    "import {card as cardClass} from './styles.module.css';",
    "cardClass",
    "card"
)]
#[case(
    "import * as styles from './styles.module.css';",
    "styles.card",
    "card"
)]
#[case("import styles from './styles.module.css';", "styles['card']", "card")]
#[case("import * as styles from './styles.module.css';", "styles", "toJSON")]
#[serial]
fn css_retention_rejects_actual_read_at_original_site_when_export_is_unknown(
    #[case] import: &str,
    #[case] read: &str,
    #[case] key: &str,
) {
    // Given: type erasure and Unicode must not shift the read's original location.
    css::file_map::reset_file_map();
    let helper =
        format!("{import}\nconst label: string='한글😀';\nexport const color: string = {read};");
    let resolver = move |specifier: &str, importer: &str| match (specifier, importer) {
        ("./helper", "/src/card.css.ts") => Some(ResolvedModule {
            path: "/src/helper.ts".to_string(),
            code: helper.clone(),
        }),
        ("./styles.module.css", "/src/helper.ts") => Some(ResolvedModule {
            path: "/src/styles.module.css".to_string(),
            code: CSS.to_string(),
        }),
        _ => None,
    };
    // When
    let error = crate::extract_with_modules(
        "/src/card.css.ts",
        ENTRY,
        ExtractOption::default(),
        false,
        &resolver,
    )
    .err()
    .map(|error| error.to_string())
    .unwrap_or_default();
    // Then
    let site = if read == "styles" {
        "/src/card.css.ts:1:88:"
    } else {
        "/src/helper.ts:3:30:"
    };
    assert!(error.starts_with(site), "{error}");
    assert!(
        error.contains("/src/styles.module.css") && error.contains(&format!("export '{key}'")),
        "{error}"
    );
    assert!(
        error.contains("generated by the bundler") && error.contains("unknown at build time"),
        "{error}"
    );
    assert!(error.contains("Fix: use the class in a runtime component (className={styles.card}) or write the style with css()"), "{error}");
    assert_eq!(error.matches("Fix:").count(), 1, "{error}");
    assert!(!error.contains("devup-ui-stylesheet"), "{error}");
}

#[rstest::rstest]
#[case("import styles from './styles.module.css';", "styles.card")]
#[case("import {card} from './styles.module.css';", "card")]
#[case("import * as styles from './styles.module.css';", "styles.card")]
#[serial]
fn css_retention_rejects_called_function_read_when_css_value_is_requested(
    #[case] import: &str,
    #[case] read: &str,
) {
    // Given
    css::file_map::reset_file_map();
    let helper = format!(
        "{import}\nfunction read(): string {{\n  return {read};\n}}\nexport const color=read();"
    );
    let resolver = move |specifier: &str, importer: &str| match (specifier, importer) {
        ("./helper", "/src/card.css.ts") => Some(ResolvedModule {
            path: "/src/helper.ts".to_string(),
            code: helper.clone(),
        }),
        ("./styles.module.css", "/src/helper.ts") => Some(ResolvedModule {
            path: "/src/styles.module.css".to_string(),
            code: CSS.to_string(),
        }),
        _ => None,
    };
    // When
    let error = crate::extract_with_modules(
        "/src/card.css.ts",
        ENTRY,
        ExtractOption::default(),
        false,
        &resolver,
    )
    .err()
    .map(|error| error.to_string())
    .unwrap_or_default();
    // Then
    assert!(error.starts_with("/src/helper.ts:3:10:"), "{error}");
    assert!(
        error.contains("export 'card'") && error.contains("/src/styles.module.css"),
        "{error}"
    );
    assert!(error.contains("at read (/src/helper.ts:3:10)"), "{error}");
    assert_eq!(error.matches("Fix:").count(), 1, "{error}");
    assert!(error.contains("Fix: use the class in a runtime component (className={styles.card}) or write the style with css()"), "{error}");
}

#[rstest::rstest]
#[case("import styles from './styles.module.css';")]
#[case("import {card} from './styles.module.css';")]
#[case("import * as styles from './styles.module.css';")]
#[serial]
fn css_retention_elides_root_unused_css_bindings_when_typescript_erases_them(
    #[case] import: &str,
) -> Result<(), String> {
    // Given
    css::file_map::reset_file_map();
    let source = format!(
        "import './before.css';{import}import './after.css';export const value=['red'].join('');"
    );
    let resolver = |_: &str, _: &str| -> Option<ResolvedModule> {
        panic!("root-only unused CSS loads remain bundler-owned")
    };
    // When
    let (_, imports) = crate::vanilla_extract::execute_stylesheet(
        &source,
        "/src/card.css.ts",
        &ExtractOption::default(),
        Some(&resolver),
    )?;
    // Then
    assert_eq!(imports.kept_imports, ["./before.css", "./after.css"]);
    Ok(())
}

#[test]
#[serial]
fn css_retention_preserves_order_when_unused_helper_bindings_are_erased() -> Result<(), String> {
    // Given
    css::file_map::reset_file_map();
    let resolver = |specifier: &str, importer: &str| {
        let (path, code) = match (specifier, importer) {
            ("./helper", "/src/card.css.ts") => (
                "/src/helper.ts",
                "import styles from './first.module.css';import './child';import {card} from './last.module.css';export const color='red';",
            ),
            ("./child", "/src/helper.ts") => ("/src/child.ts", "import './child.css';"),
            ("./first.module.css", "/src/helper.ts") => ("/src/first.module.css", CSS),
            ("./last.module.css", "/src/helper.ts") => ("/src/last.module.css", CSS),
            ("./child.css", "/src/child.ts") => ("/src/child.css", CSS),
            _ => return None,
        };
        Some(ResolvedModule {
            path: path.to_string(),
            code: code.to_string(),
        })
    };
    // When
    let (_, imports) = crate::vanilla_extract::execute_stylesheet(
        "import {color} from './helper';export const value=color;",
        "/src/card.css.ts",
        &ExtractOption::default(),
        Some(&resolver),
    )?;
    // Then
    assert_eq!(imports.kept_imports, ["./child.css"]);
    Ok(())
}

#[test]
#[serial]
fn css_retention_ignores_type_only_imports_when_no_css_is_loaded() -> Result<(), String> {
    // Given
    css::file_map::reset_file_map();
    let source = "import type Styles from './styles.module.css';import {type Card} from './other.module.css';export const color='red';";
    let resolver = |_: &str, _: &str| -> Option<ResolvedModule> {
        panic!("type-only CSS must not be resolved")
    };
    // When
    let (_, imports) = crate::vanilla_extract::execute_stylesheet(
        source,
        "/src/card.css.ts",
        &ExtractOption::default(),
        Some(&resolver),
    )?;
    // Then
    assert_eq!(imports.kept_imports, Vec::<String>::new());
    Ok(())
}
