// AUTO-GENERATED by apps/landing/script.js - do not edit by hand.
// Run `node ./script.js` (part of `dev`, `build` and `build:next`) to refresh.
import type { ComponentType } from 'react'

import demo0 from '../app/(detail)/components/[component]/button/demo/1_Variants'
import demo1 from '../app/(detail)/components/[component]/button/demo/2_Icon'
import demo2 from '../app/(detail)/components/[component]/button/demo/3_Danger'
import demo3 from '../app/(detail)/components/[component]/button/demo/4_Disabled'
import demo4 from '../app/(detail)/components/[component]/button/demo/5_Colors'
import demo5 from '../app/(detail)/components/[component]/checkbox/demo/1_Default'
import demo6 from '../app/(detail)/components/[component]/checkbox/demo/2_Checked'
import demo7 from '../app/(detail)/components/[component]/checkbox/demo/3_Disabled'
import demo8 from '../app/(detail)/components/[component]/checkbox/demo/4_Colors'
import demo9 from '../app/(detail)/components/[component]/radio/demo/1_Default'
import demo10 from '../app/(detail)/components/[component]/radio/demo/2_Variant'
import demo11 from '../app/(detail)/components/[component]/radio/demo/3_Direction'
import demo12 from '../app/(detail)/components/[component]/radio/demo/4_Disabled'
import demo13 from '../app/(detail)/components/[component]/select/demo/1_Default'
import demo14 from '../app/(detail)/components/[component]/select/demo/2_Radio'
import demo15 from '../app/(detail)/components/[component]/select/demo/3_Checkbox'
import demo16 from '../app/(detail)/components/[component]/select/demo/4_Options'
import demo17 from '../app/(detail)/components/[component]/stepper/demo/1_Default'
import demo18 from '../app/(detail)/components/[component]/stepper/demo/2_Type'
import demo19 from '../app/(detail)/components/[component]/stepper/demo/3_MinMax'
import demo20 from '../app/(detail)/components/[component]/textarea/demo/1_Default'
import demo21 from '../app/(detail)/components/[component]/textarea/demo/2_Error'
import demo22 from '../app/(detail)/components/[component]/textarea/demo/3_Disabled'
import demo23 from '../app/(detail)/components/[component]/textarea/demo/4_Colors'
import demo24 from '../app/(detail)/components/[component]/textbox/demo/1_Default'
import demo25 from '../app/(detail)/components/[component]/textbox/demo/2_Error'
import demo26 from '../app/(detail)/components/[component]/textbox/demo/3_Disabled'
import demo27 from '../app/(detail)/components/[component]/textbox/demo/4_Icon'
import demo28 from '../app/(detail)/components/[component]/toggle/demo/1_Default'
import demo29 from '../app/(detail)/components/[component]/toggle/demo/2_Variant'
import demo30 from '../app/(detail)/components/[component]/toggle/demo/3_Disabled'
import demo31 from '../app/(detail)/components/[component]/toggle/demo/4_Colors'

export const DEMOS: readonly (readonly [string, ComponentType])[] = [
  ['button/demo/1_Variants.tsx', demo0],
  ['button/demo/2_Icon.tsx', demo1],
  ['button/demo/3_Danger.tsx', demo2],
  ['button/demo/4_Disabled.tsx', demo3],
  ['button/demo/5_Colors.tsx', demo4],
  ['checkbox/demo/1_Default.tsx', demo5],
  ['checkbox/demo/2_Checked.tsx', demo6],
  ['checkbox/demo/3_Disabled.tsx', demo7],
  ['checkbox/demo/4_Colors.tsx', demo8],
  ['radio/demo/1_Default.tsx', demo9],
  ['radio/demo/2_Variant.tsx', demo10],
  ['radio/demo/3_Direction.tsx', demo11],
  ['radio/demo/4_Disabled.tsx', demo12],
  ['select/demo/1_Default.tsx', demo13],
  ['select/demo/2_Radio.tsx', demo14],
  ['select/demo/3_Checkbox.tsx', demo15],
  ['select/demo/4_Options.tsx', demo16],
  ['stepper/demo/1_Default.tsx', demo17],
  ['stepper/demo/2_Type.tsx', demo18],
  ['stepper/demo/3_MinMax.tsx', demo19],
  ['textarea/demo/1_Default.tsx', demo20],
  ['textarea/demo/2_Error.tsx', demo21],
  ['textarea/demo/3_Disabled.tsx', demo22],
  ['textarea/demo/4_Colors.tsx', demo23],
  ['textbox/demo/1_Default.tsx', demo24],
  ['textbox/demo/2_Error.tsx', demo25],
  ['textbox/demo/3_Disabled.tsx', demo26],
  ['textbox/demo/4_Icon.tsx', demo27],
  ['toggle/demo/1_Default.tsx', demo28],
  ['toggle/demo/2_Variant.tsx', demo29],
  ['toggle/demo/3_Disabled.tsx', demo30],
  ['toggle/demo/4_Colors.tsx', demo31],
]
